/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : VTBM_enable.H
**     Project   : Project
**     Processor : MC9S12XEP100MAL
**     Beantype  : BitIO
**     Version   : Bean 02.072, Driver 03.12, CPU db: 3.00.016
**     Compiler  : CodeWarrior HCS12X C Compiler
**     Date/Time : 2015/9/6, 10:13
**     Abstract  :
**         This bean "BitIO" implements an one-bit input/output.
**         It uses one bit/pin of a port.
**         Note: This bean is set to work in Output direction only.
**         Methods of this bean are mostly implemented as a macros
**         (if supported by target language and compiler).
**     Settings  :
**         Used pin                    :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       31            |  PB7
**             ----------------------------------------------------
**
**         Port name                   : B
**
**         Bit number (in port)        : 7
**         Bit mask of the port        : $0080
**
**         Initial direction           : Output (direction cannot be changed)
**         Initial output value        : 0
**         Initial pull option         : off
**
**         Port data register          : PORTB     [$0001]
**         Port control register       : DDRB      [$0003]
**
**         Optimization for            : speed
**     Contents  :
**         GetVal - bool VTBM_enable_GetVal(void);
**         PutVal - void VTBM_enable_PutVal(bool Val);
**         ClrVal - void VTBM_enable_ClrVal(void);
**         SetVal - void VTBM_enable_SetVal(void);
**
**     (c) Copyright UNIS, a.s. 1997-2008
**     UNIS, a.s.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################*/

#ifndef VTBM_enable_H_
#define VTBM_enable_H_

/* MODULE VTBM_enable. */

  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"

#pragma CODE_SEG VTBM_enable_CODE
/*
** ===================================================================
**     Method      :  VTBM_enable_GetVal (bean BitIO)
**
**     Description :
**         This method returns an input value.
**           a) direction = Input  : reads the input value from the
**                                   pin and returns it
**           b) direction = Output : returns the last written value
**         Note: This bean is set to work in Output direction only.
**     Parameters  : None
**     Returns     :
**         ---             - Input value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)

** ===================================================================
*/
#define VTBM_enable_GetVal() ( \
    (bool_t)((getReg8(PORTB) & 0x80))    /* Return port data */ \
  )

/*
** ===================================================================
**     Method      :  VTBM_enable_PutVal (bean BitIO)
**
**     Description :
**         This method writes the new output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Val             - Output value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)
**     Returns     : Nothing
** ===================================================================
*/
//void VTBM_enable_PutVal(bool Val);
void VTBM_enable_PutVal(bool_t Val);

/*
** ===================================================================
**     Method      :  VTBM_enable_ClrVal (bean BitIO)
**
**     Description :
**         This method clears (sets to zero) the output value.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
#define VTBM_enable_ClrVal() ( \
    (void)clrReg8Bits(PORTB, 0x80)     /* PB7=0x00 */ \
  )

/*
** ===================================================================
**     Method      :  VTBM_enable_SetVal (bean BitIO)
**
**     Description :
**         This method sets (sets to one) the output value.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
#define VTBM_enable_SetVal() ( \
    (void)setReg8Bits(PORTB, 0x80)     /* PB7=0x01 */ \
  )

#pragma CODE_SEG DEFAULT

/* END VTBM_enable. */
#endif /* #ifndef __VTBM_enable_H_ */
/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 3.00 [04.12]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
