/*****************************************************************************
 *
 * Copyright (c) Linkedriving Tech 2015 - All rights reserved 
 *
 * file name:    ut_canbedded_stubs.c
 *
 * description:  
 * CANbedded stub file
 * 
 *
 * revision history:
 *
 * Date        Author           Description
 * 2015-Aug-10 Rui Li           initial version
 *
 *****************************************************************************/
/*
 * CANbedded stub file
 * Automatically generated by: ut_canbedded_stubber.py 8366 2013-04-25 09:11:12Z vs7 
 * 
 * 	<node>	<file>
 * 	BMS	vehicle.dbc
 * 	mmc	isa_control.dbc
 * 	BMS	charger.dbc
 */
#include "basic_types.h"
#include "ut_canbedded_stubs.h"
#ifndef HOSTED
#include "ccl_inc.h"
#include "v_inc.h"
#endif

bool_t ut_cbd_override = TRUE;

PRIVATE void ut_memcpy(uint8_t * dest, uint8_t * src, uint16_t len)
{
    uint16_t i;
    for (i = 0u; i < len; i++)
    {
        *dest++ = *src++;
    }
}

/* Rx signals source start */
uint8_t ut_NSBCPTStatusChecksum_get;
uint32_t ut_NSBCPTStatusChecksum_get_ctr;
uint8_t ut_IlGetRxNSBCPTStatusChecksum(void)
{
    ut_NSBCPTStatusChecksum_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_NSBCPTStatusChecksum_get = IlGetRxNSBCPTStatusChecksum();
    }
    #endif
    return ut_NSBCPTStatusChecksum_get;
}


uint16_t ut_PID43_AbsoluteLoad_get;
uint32_t ut_PID43_AbsoluteLoad_get_ctr;
uint16_t ut_IlGetRxPID43_AbsoluteLoad(void)
{
    ut_PID43_AbsoluteLoad_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_PID43_AbsoluteLoad_get = IlGetRxPID43_AbsoluteLoad();
    }
    #endif
    return ut_PID43_AbsoluteLoad_get;
}


uint8_t ut_PID49_AbsolutePedalPosn_get;
uint32_t ut_PID49_AbsolutePedalPosn_get_ctr;
uint8_t ut_IlGetRxPID49_AbsolutePedalPosn(void)
{
    ut_PID49_AbsolutePedalPosn_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_PID49_AbsolutePedalPosn_get = IlGetRxPID49_AbsolutePedalPosn();
    }
    #endif
    return ut_PID49_AbsolutePedalPosn_get;
}


uint8_t ut_NBatteryType_get;
uint32_t ut_NBatteryType_get_ctr;
uint8_t ut_IlGetRxNBatteryType(void)
{
    ut_NBatteryType_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_NBatteryType_get = IlGetRxNBatteryType();
    }
    #endif
    return ut_NBatteryType_get;
}


uint16_t ut_PID0C_nEngine_get;
uint32_t ut_PID0C_nEngine_get_ctr;
uint16_t ut_IlGetRxPID0C_nEngine(void)
{
    ut_PID0C_nEngine_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_PID0C_nEngine_get = IlGetRxPID0C_nEngine();
    }
    #endif
    return ut_PID0C_nEngine_get;
}


uint8_t ut_PID05_TEngineCoolant_get;
uint32_t ut_PID05_TEngineCoolant_get_ctr;
uint8_t ut_IlGetRxPID05_TEngineCoolant(void)
{
    ut_PID05_TEngineCoolant_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_PID05_TEngineCoolant_get = IlGetRxPID05_TEngineCoolant();
    }
    #endif
    return ut_PID05_TEngineCoolant_get;
}


uint8_t ut_tSecond_get;
uint32_t ut_tSecond_get_ctr;
uint8_t ut_IlGetRxtSecond(void)
{
    ut_tSecond_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_tSecond_get = IlGetRxtSecond();
    }
    #endif
    return ut_tSecond_get;
}


uint8_t ut_NECM_BMS_00Checksum_get;
uint32_t ut_NECM_BMS_00Checksum_get_ctr;
uint8_t ut_IlGetRxNECM_BMS_00Checksum(void)
{
    ut_NECM_BMS_00Checksum_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_NECM_BMS_00Checksum_get = IlGetRxNECM_BMS_00Checksum();
    }
    #endif
    return ut_NECM_BMS_00Checksum_get;
}


uint16_t ut_nPowertrain_get;
uint32_t ut_nPowertrain_get_ctr;
uint16_t ut_IlGetRxnPowertrain(void)
{
    ut_nPowertrain_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_nPowertrain_get = IlGetRxnPowertrain();
    }
    #endif
    return ut_nPowertrain_get;
}


uint8_t ut_NCarConfigMultiplexor_get;
uint32_t ut_NCarConfigMultiplexor_get_ctr;
uint8_t ut_IlGetRxNCarConfigMultiplexor(void)
{
    ut_NCarConfigMultiplexor_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_NCarConfigMultiplexor_get = IlGetRxNCarConfigMultiplexor();
    }
    #endif
    return ut_NCarConfigMultiplexor_get;
}


uint8_t ut_NIgnitionStatus_get;
uint32_t ut_NIgnitionStatus_get_ctr;
uint8_t ut_IlGetRxNIgnitionStatus(void)
{
    ut_NIgnitionStatus_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_NIgnitionStatus_get = IlGetRxNIgnitionStatus();
    }
    #endif
    return ut_NIgnitionStatus_get;
}


uint8_t ut_NCCU_1Checksum_get;
uint32_t ut_NCCU_1Checksum_get_ctr;
uint8_t ut_IlGetRxNCCU_1Checksum(void)
{
    ut_NCCU_1Checksum_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_NCCU_1Checksum_get = IlGetRxNCCU_1Checksum();
    }
    #endif
    return ut_NCCU_1Checksum_get;
}


uint8_t ut_NMCUStatus_get;
uint32_t ut_NMCUStatus_get_ctr;
uint8_t ut_IlGetRxNMCUStatus(void)
{
    ut_NMCUStatus_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_NMCUStatus_get = IlGetRxNMCUStatus();
    }
    #endif
    return ut_NMCUStatus_get;
}


uint8_t ut_tDay_get;
uint32_t ut_tDay_get_ctr;
uint8_t ut_IlGetRxtDay(void)
{
    ut_tDay_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_tDay_get = IlGetRxtDay();
    }
    #endif
    return ut_tDay_get;
}


uint16_t ut_vVehicleIC_get;
uint32_t ut_vVehicleIC_get_ctr;
uint16_t ut_IlGetRxvVehicleIC(void)
{
    ut_vVehicleIC_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_vVehicleIC_get = IlGetRxvVehicleIC();
    }
    #endif
    return ut_vVehicleIC_get;
}


uint8_t ut_qWaterPumpHybridCooling_get;
uint32_t ut_qWaterPumpHybridCooling_get_ctr;
uint8_t ut_IlGetRxqWaterPumpHybridCooling(void)
{
    ut_qWaterPumpHybridCooling_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_qWaterPumpHybridCooling_get = IlGetRxqWaterPumpHybridCooling();
    }
    #endif
    return ut_qWaterPumpHybridCooling_get;
}


uint8_t ut_NContactorRequested_get;
uint32_t ut_NContactorRequested_get_ctr;
uint8_t ut_IlGetRxNContactorRequested(void)
{
    ut_NContactorRequested_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_NContactorRequested_get = IlGetRxNContactorRequested();
    }
    #endif
    return ut_NContactorRequested_get;
}


uint8_t ut_NPowertrainStatus_get;
uint32_t ut_NPowertrainStatus_get_ctr;
uint8_t ut_IlGetRxNPowertrainStatus(void)
{
    ut_NPowertrainStatus_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_NPowertrainStatus_get = IlGetRxNPowertrainStatus();
    }
    #endif
    return ut_NPowertrainStatus_get;
}


uint8_t ut_NEngineStatus_get;
uint32_t ut_NEngineStatus_get_ctr;
uint8_t ut_IlGetRxNEngineStatus(void)
{
    ut_NEngineStatus_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_NEngineStatus_get = IlGetRxNEngineStatus();
    }
    #endif
    return ut_NEngineStatus_get;
}


uint8_t ut_NECM_BMS_00Counter_get;
uint32_t ut_NECM_BMS_00Counter_get_ctr;
uint8_t ut_IlGetRxNECM_BMS_00Counter(void)
{
    ut_NECM_BMS_00Counter_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_NECM_BMS_00Counter_get = IlGetRxNECM_BMS_00Counter();
    }
    #endif
    return ut_NECM_BMS_00Counter_get;
}


uint8_t ut_NMCU_3Checksum_get;
uint32_t ut_NMCU_3Checksum_get_ctr;
uint8_t ut_IlGetRxNMCU_3Checksum(void)
{
    ut_NMCU_3Checksum_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_NMCU_3Checksum_get = IlGetRxNMCU_3Checksum();
    }
    #endif
    return ut_NMCU_3Checksum_get;
}


uint8_t ut_tMonth_get;
uint32_t ut_tMonth_get_ctr;
uint8_t ut_IlGetRxtMonth(void)
{
    ut_tMonth_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_tMonth_get = IlGetRxtMonth();
    }
    #endif
    return ut_tMonth_get;
}


uint8_t ut_tYear_get;
uint32_t ut_tYear_get_ctr;
uint8_t ut_IlGetRxtYear(void)
{
    ut_tYear_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_tYear_get = IlGetRxtYear();
    }
    #endif
    return ut_tYear_get;
}


uint8_t ut_NVINDataBytesIndex_get;
uint32_t ut_NVINDataBytesIndex_get_ctr;
uint8_t ut_IlGetRxNVINDataBytesIndex(void)
{
    ut_NVINDataBytesIndex_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_NVINDataBytesIndex_get = IlGetRxNVINDataBytesIndex();
    }
    #endif
    return ut_NVINDataBytesIndex_get;
}


uint8_t ut_NVINPart2_get[7];
uint32_t ut_NVINPart2_get_ctr;
void ut_IlGetRxNVINPart2(uint8_t * out)
{
    ut_NVINPart2_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlGetRxNVINPart2(ut_NVINPart2_get);
    }
    #endif
    ut_memcpy(out, ut_NVINPart2_get, sizeof(ut_NVINPart2_get));
}


uint8_t ut_NVINPart1_get[7];
uint32_t ut_NVINPart1_get_ctr;
void ut_IlGetRxNVINPart1(uint8_t * out)
{
    ut_NVINPart1_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlGetRxNVINPart1(ut_NVINPart1_get);
    }
    #endif
    ut_memcpy(out, ut_NVINPart1_get, sizeof(ut_NVINPart1_get));
}


uint8_t ut_tMinute_get;
uint32_t ut_tMinute_get_ctr;
uint8_t ut_IlGetRxtMinute(void)
{
    ut_tMinute_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_tMinute_get = IlGetRxtMinute();
    }
    #endif
    return ut_tMinute_get;
}


uint8_t ut_NSBCPTStatusCounter_get;
uint32_t ut_NSBCPTStatusCounter_get_ctr;
uint8_t ut_IlGetRxNSBCPTStatusCounter(void)
{
    ut_NSBCPTStatusCounter_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_NSBCPTStatusCounter_get = IlGetRxNSBCPTStatusCounter();
    }
    #endif
    return ut_NSBCPTStatusCounter_get;
}


uint32_t ut_lPART1Totalizer_get;
uint32_t ut_lPART1Totalizer_get_ctr;
uint32_t ut_IlGetRxlPART1Totalizer(void)
{
    ut_lPART1Totalizer_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_lPART1Totalizer_get = IlGetRxlPART1Totalizer();
    }
    #endif
    return ut_lPART1Totalizer_get;
}


uint32_t ut_NVINPart3_get;
uint32_t ut_NVINPart3_get_ctr;
uint32_t ut_IlGetRxNVINPart3(void)
{
    ut_NVINPart3_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_NVINPart3_get = IlGetRxNVINPart3();
    }
    #endif
    return ut_NVINPart3_get;
}


uint16_t ut_PID0D_vVehicleOBD_get;
uint32_t ut_PID0D_vVehicleOBD_get_ctr;
uint16_t ut_IlGetRxPID0D_vVehicleOBD(void)
{
    ut_PID0D_vVehicleOBD_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_PID0D_vVehicleOBD_get = IlGetRxPID0D_vVehicleOBD();
    }
    #endif
    return ut_PID0D_vVehicleOBD_get;
}


uint8_t ut_PID04_CalculatedLoad_get;
uint32_t ut_PID04_CalculatedLoad_get_ctr;
uint8_t ut_IlGetRxPID04_CalculatedLoad(void)
{
    ut_PID04_CalculatedLoad_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_PID04_CalculatedLoad_get = IlGetRxPID04_CalculatedLoad();
    }
    #endif
    return ut_PID04_CalculatedLoad_get;
}


uint8_t ut_BTBatteryHighLimitEnable_get;
uint32_t ut_BTBatteryHighLimitEnable_get_ctr;
uint8_t ut_IlGetRxBTBatteryHighLimitEnable(void)
{
    ut_BTBatteryHighLimitEnable_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_BTBatteryHighLimitEnable_get = IlGetRxBTBatteryHighLimitEnable();
    }
    #endif
    return ut_BTBatteryHighLimitEnable_get;
}


uint8_t ut_NMCU_3Counter_get;
uint32_t ut_NMCU_3Counter_get_ctr;
uint8_t ut_IlGetRxNMCU_3Counter(void)
{
    ut_NMCU_3Counter_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_NMCU_3Counter_get = IlGetRxNMCU_3Counter();
    }
    #endif
    return ut_NMCU_3Counter_get;
}


uint8_t ut_VBattery_get;
uint32_t ut_VBattery_get_ctr;
uint8_t ut_IlGetRxVBattery(void)
{
    ut_VBattery_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_VBattery_get = IlGetRxVBattery();
    }
    #endif
    return ut_VBattery_get;
}


uint8_t ut_IDCDCOutput_get;
uint32_t ut_IDCDCOutput_get_ctr;
uint8_t ut_IlGetRxIDCDCOutput(void)
{
    ut_IDCDCOutput_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_IDCDCOutput_get = IlGetRxIDCDCOutput();
    }
    #endif
    return ut_IDCDCOutput_get;
}


uint8_t ut_PID33_BarometricPressure_get;
uint32_t ut_PID33_BarometricPressure_get_ctr;
uint8_t ut_IlGetRxPID33_BarometricPressure(void)
{
    ut_PID33_BarometricPressure_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_PID33_BarometricPressure_get = IlGetRxPID33_BarometricPressure();
    }
    #endif
    return ut_PID33_BarometricPressure_get;
}


uint8_t ut_NGearEngaged_get;
uint32_t ut_NGearEngaged_get_ctr;
uint8_t ut_IlGetRxNGearEngaged(void)
{
    ut_NGearEngaged_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_NGearEngaged_get = IlGetRxNGearEngaged();
    }
    #endif
    return ut_NGearEngaged_get;
}


uint8_t ut_PID4A_AbsolutePedalPosn_get;
uint32_t ut_PID4A_AbsolutePedalPosn_get_ctr;
uint8_t ut_IlGetRxPID4A_AbsolutePedalPosn(void)
{
    ut_PID4A_AbsolutePedalPosn_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_PID4A_AbsolutePedalPosn_get = IlGetRxPID4A_AbsolutePedalPosn();
    }
    #endif
    return ut_PID4A_AbsolutePedalPosn_get;
}


uint8_t ut_tHour_get;
uint32_t ut_tHour_get_ctr;
uint8_t ut_IlGetRxtHour(void)
{
    ut_tHour_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_tHour_get = IlGetRxtHour();
    }
    #endif
    return ut_tHour_get;
}


uint8_t ut_NMCU_4Checksum_get;
uint32_t ut_NMCU_4Checksum_get_ctr;
uint8_t ut_IlGetRxNMCU_4Checksum(void)
{
    ut_NMCU_4Checksum_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_NMCU_4Checksum_get = IlGetRxNMCU_4Checksum();
    }
    #endif
    return ut_NMCU_4Checksum_get;
}


uint8_t ut_NEPBEngaged_get;
uint32_t ut_NEPBEngaged_get_ctr;
uint8_t ut_IlGetRxNEPBEngaged(void)
{
    ut_NEPBEngaged_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_NEPBEngaged_get = IlGetRxNEPBEngaged();
    }
    #endif
    return ut_NEPBEngaged_get;
}


uint8_t ut_NCCU_1Counter_get;
uint32_t ut_NCCU_1Counter_get_ctr;
uint8_t ut_IlGetRxNCCU_1Counter(void)
{
    ut_NCCU_1Counter_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_NCCU_1Counter_get = IlGetRxNCCU_1Counter();
    }
    #endif
    return ut_NCCU_1Counter_get;
}


uint8_t ut_NCrashSeverity_get;
uint32_t ut_NCrashSeverity_get_ctr;
uint8_t ut_IlGetRxNCrashSeverity(void)
{
    ut_NCrashSeverity_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_NCrashSeverity_get = IlGetRxNCrashSeverity();
    }
    #endif
    return ut_NCrashSeverity_get;
}


uint8_t ut_NMCU_4Counter_get;
uint32_t ut_NMCU_4Counter_get_ctr;
uint8_t ut_IlGetRxNMCU_4Counter(void)
{
    ut_NMCU_4Counter_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_NMCU_4Counter_get = IlGetRxNMCU_4Counter();
    }
    #endif
    return ut_NMCU_4Counter_get;
}


uint8_t ut_TAmbientRaw_get;
uint32_t ut_TAmbientRaw_get_ctr;
uint8_t ut_IlGetRxTAmbientRaw(void)
{
    ut_TAmbientRaw_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_TAmbientRaw_get = IlGetRxTAmbientRaw();
    }
    #endif
    return ut_TAmbientRaw_get;
}


uint8_t ut_IMCUDCLink_get;
uint32_t ut_IMCUDCLink_get_ctr;
uint8_t ut_IlGetRxIMCUDCLink(void)
{
    ut_IMCUDCLink_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_IMCUDCLink_get = IlGetRxIMCUDCLink();
    }
    #endif
    return ut_IMCUDCLink_get;
}


/* Tx signals source start */
uint8_t ut_Additional_BMS_Errors_1_put;
uint32_t ut_Additional_BMS_Errors_1_put_ctr;
void ut_IlPutTxAdditional_BMS_Errors_1(uint8_t val)
{
    ut_Additional_BMS_Errors_1_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxAdditional_BMS_Errors_1(val);
    }
    #endif
    ut_Additional_BMS_Errors_1_put = val;
}


uint8_t ut_Additional_BMS_Errors_2_put;
uint32_t ut_Additional_BMS_Errors_2_put_ctr;
void ut_IlPutTxAdditional_BMS_Errors_2(uint8_t val)
{
    ut_Additional_BMS_Errors_2_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxAdditional_BMS_Errors_2(val);
    }
    #endif
    ut_Additional_BMS_Errors_2_put = val;
}


uint8_t ut_Additional_BMS_Errors_3_put;
uint32_t ut_Additional_BMS_Errors_3_put_ctr;
void ut_IlPutTxAdditional_BMS_Errors_3(uint8_t val)
{
    ut_Additional_BMS_Errors_3_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxAdditional_BMS_Errors_3(val);
    }
    #endif
    ut_Additional_BMS_Errors_3_put = val;
}


uint8_t ut_Additional_BMS_Errors_SubType_3_put;
uint32_t ut_Additional_BMS_Errors_SubType_3_put_ctr;
void ut_IlPutTxAdditional_BMS_Errors_SubType_3(uint8_t val)
{
    ut_Additional_BMS_Errors_SubType_3_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxAdditional_BMS_Errors_SubType_3(val);
    }
    #endif
    ut_Additional_BMS_Errors_SubType_3_put = val;
}


uint8_t ut_Additional_BMS_Errors_SubType_2_put;
uint32_t ut_Additional_BMS_Errors_SubType_2_put_ctr;
void ut_IlPutTxAdditional_BMS_Errors_SubType_2(uint8_t val)
{
    ut_Additional_BMS_Errors_SubType_2_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxAdditional_BMS_Errors_SubType_2(val);
    }
    #endif
    ut_Additional_BMS_Errors_SubType_2_put = val;
}


uint8_t ut_Additional_BMS_Errors_SubType_1_put;
uint32_t ut_Additional_BMS_Errors_SubType_1_put_ctr;
void ut_IlPutTxAdditional_BMS_Errors_SubType_1(uint8_t val)
{
    ut_Additional_BMS_Errors_SubType_1_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxAdditional_BMS_Errors_SubType_1(val);
    }
    #endif
    ut_Additional_BMS_Errors_SubType_1_put = val;
}


uint8_t ut_NTCellMin_put;
uint32_t ut_NTCellMin_put_ctr;
void ut_IlPutTxNTCellMin(uint8_t val)
{
    ut_NTCellMin_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNTCellMin(val);
    }
    #endif
    ut_NTCellMin_put = val;
}


uint8_t ut_NVCellMin_put;
uint32_t ut_NVCellMin_put_ctr;
void ut_IlPutTxNVCellMin(uint8_t val)
{
    ut_NVCellMin_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNVCellMin(val);
    }
    #endif
    ut_NVCellMin_put = val;
}


uint8_t ut_NVCellMax_put;
uint32_t ut_NVCellMax_put_ctr;
void ut_IlPutTxNVCellMax(uint8_t val)
{
    ut_NVCellMax_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNVCellMax(val);
    }
    #endif
    ut_NVCellMax_put = val;
}


uint16_t ut_VCellSOCMin_put;
uint32_t ut_VCellSOCMin_put_ctr;
void ut_IlPutTxVCellSOCMin(uint16_t val)
{
    ut_VCellSOCMin_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxVCellSOCMin(val);
    }
    #endif
    ut_VCellSOCMin_put = val;
}


uint16_t ut_VCellSOCMax_put;
uint32_t ut_VCellSOCMax_put_ctr;
void ut_IlPutTxVCellSOCMax(uint16_t val)
{
    ut_VCellSOCMax_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxVCellSOCMax(val);
    }
    #endif
    ut_VCellSOCMax_put = val;
}


uint8_t ut_NTCellMax_put;
uint32_t ut_NTCellMax_put_ctr;
void ut_IlPutTxNTCellMax(uint8_t val)
{
    ut_NTCellMax_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNTCellMax(val);
    }
    #endif
    ut_NTCellMax_put = val;
}


uint8_t ut_ctc_marker_put;
uint32_t ut_ctc_marker_put_ctr;
void ut_IlPutTxctc_marker(uint8_t val)
{
    ut_ctc_marker_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxctc_marker(val);
    }
    #endif
    ut_ctc_marker_put = val;
}


uint16_t ut_ctc_overall_voltage_put;
uint32_t ut_ctc_overall_voltage_put_ctr;
void ut_IlPutTxctc_overall_voltage(uint16_t val)
{
    ut_ctc_overall_voltage_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxctc_overall_voltage(val);
    }
    #endif
    ut_ctc_overall_voltage_put = val;
}


uint16_t ut_ctc_pos_voltage_put;
uint32_t ut_ctc_pos_voltage_put_ctr;
void ut_IlPutTxctc_pos_voltage(uint16_t val)
{
    ut_ctc_pos_voltage_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxctc_pos_voltage(val);
    }
    #endif
    ut_ctc_pos_voltage_put = val;
}


uint8_t ut_ctc_save_seq_put;
uint32_t ut_ctc_save_seq_put_ctr;
void ut_IlPutTxctc_save_seq(uint8_t val)
{
    ut_ctc_save_seq_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxctc_save_seq(val);
    }
    #endif
    ut_ctc_save_seq_put = val;
}


uint16_t ut_ctc_latest_imi_put;
uint32_t ut_ctc_latest_imi_put_ctr;
void ut_IlPutTxctc_latest_imi(uint16_t val)
{
    ut_ctc_latest_imi_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxctc_latest_imi(val);
    }
    #endif
    ut_ctc_latest_imi_put = val;
}


uint8_t ut_NBMS_3AChecksum_put;
uint32_t ut_NBMS_3AChecksum_put_ctr;
void ut_IlPutTxNBMS_3AChecksum(uint8_t val)
{
    ut_NBMS_3AChecksum_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNBMS_3AChecksum(val);
    }
    #endif
    ut_NBMS_3AChecksum_put = val;
}


uint16_t ut_NBMS_FirstFaultCode_put;
uint32_t ut_NBMS_FirstFaultCode_put_ctr;
void ut_IlPutTxNBMS_FirstFaultCode(uint16_t val)
{
    ut_NBMS_FirstFaultCode_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNBMS_FirstFaultCode(val);
    }
    #endif
    ut_NBMS_FirstFaultCode_put = val;
}


uint16_t ut_NBMS_SecondFaultCode_put;
uint32_t ut_NBMS_SecondFaultCode_put_ctr;
void ut_IlPutTxNBMS_SecondFaultCode(uint16_t val)
{
    ut_NBMS_SecondFaultCode_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNBMS_SecondFaultCode(val);
    }
    #endif
    ut_NBMS_SecondFaultCode_put = val;
}


uint16_t ut_NBMS_RecentFaultCode_put;
uint32_t ut_NBMS_RecentFaultCode_put_ctr;
void ut_IlPutTxNBMS_RecentFaultCode(uint16_t val)
{
    ut_NBMS_RecentFaultCode_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNBMS_RecentFaultCode(val);
    }
    #endif
    ut_NBMS_RecentFaultCode_put = val;
}


uint8_t ut_NBMS_3ACounter_put;
uint32_t ut_NBMS_3ACounter_put_ctr;
void ut_IlPutTxNBMS_3ACounter(uint8_t val)
{
    ut_NBMS_3ACounter_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNBMS_3ACounter(val);
    }
    #endif
    ut_NBMS_3ACounter_put = val;
}


uint8_t ut_bms_dbg_39_0_put;
uint32_t ut_bms_dbg_39_0_put_ctr;
void ut_IlPutTxbms_dbg_39_0(uint8_t val)
{
    ut_bms_dbg_39_0_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxbms_dbg_39_0(val);
    }
    #endif
    ut_bms_dbg_39_0_put = val;
}


uint8_t ut_bms_dbg_39_1_put;
uint32_t ut_bms_dbg_39_1_put_ctr;
void ut_IlPutTxbms_dbg_39_1(uint8_t val)
{
    ut_bms_dbg_39_1_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxbms_dbg_39_1(val);
    }
    #endif
    ut_bms_dbg_39_1_put = val;
}


uint8_t ut_bms_dbg_39_4_put;
uint32_t ut_bms_dbg_39_4_put_ctr;
void ut_IlPutTxbms_dbg_39_4(uint8_t val)
{
    ut_bms_dbg_39_4_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxbms_dbg_39_4(val);
    }
    #endif
    ut_bms_dbg_39_4_put = val;
}


uint8_t ut_bms_dbg_39_5_put;
uint32_t ut_bms_dbg_39_5_put_ctr;
void ut_IlPutTxbms_dbg_39_5(uint8_t val)
{
    ut_bms_dbg_39_5_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxbms_dbg_39_5(val);
    }
    #endif
    ut_bms_dbg_39_5_put = val;
}


uint8_t ut_bms_dbg_39_6_put;
uint32_t ut_bms_dbg_39_6_put_ctr;
void ut_IlPutTxbms_dbg_39_6(uint8_t val)
{
    ut_bms_dbg_39_6_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxbms_dbg_39_6(val);
    }
    #endif
    ut_bms_dbg_39_6_put = val;
}


uint8_t ut_bms_dbg_39_7_put;
uint32_t ut_bms_dbg_39_7_put_ctr;
void ut_IlPutTxbms_dbg_39_7(uint8_t val)
{
    ut_bms_dbg_39_7_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxbms_dbg_39_7(val);
    }
    #endif
    ut_bms_dbg_39_7_put = val;
}


uint8_t ut_SOCcLow_put;
uint32_t ut_SOCcLow_put_ctr;
void ut_IlPutTxSOCcLow(uint8_t val)
{
    ut_SOCcLow_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxSOCcLow(val);
    }
    #endif
    ut_SOCcLow_put = val;
}


uint8_t ut_SOCcHigh_put;
uint32_t ut_SOCcHigh_put_ctr;
void ut_IlPutTxSOCcHigh(uint8_t val)
{
    ut_SOCcHigh_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxSOCcHigh(val);
    }
    #endif
    ut_SOCcHigh_put = val;
}


uint8_t ut_ctc_no_close_reason_put;
uint32_t ut_ctc_no_close_reason_put_ctr;
void ut_IlPutTxctc_no_close_reason(uint8_t val)
{
    ut_ctc_no_close_reason_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxctc_no_close_reason(val);
    }
    #endif
    ut_ctc_no_close_reason_put = val;
}


uint8_t ut_bms_dbg_38_1_put;
uint32_t ut_bms_dbg_38_1_put_ctr;
void ut_IlPutTxbms_dbg_38_1(uint8_t val)
{
    ut_bms_dbg_38_1_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxbms_dbg_38_1(val);
    }
    #endif
    ut_bms_dbg_38_1_put = val;
}


uint8_t ut_bms_dbg_38_0_put;
uint32_t ut_bms_dbg_38_0_put_ctr;
void ut_IlPutTxbms_dbg_38_0(uint8_t val)
{
    ut_bms_dbg_38_0_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxbms_dbg_38_0(val);
    }
    #endif
    ut_bms_dbg_38_0_put = val;
}


int32_t ut_IRaw_put;
uint32_t ut_IRaw_put_ctr;
void ut_IlPutTxIRaw(int32_t val)
{
    ut_IRaw_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxIRaw(val);
    }
    #endif
    ut_IRaw_put = val;
}


uint8_t ut_bms_dbg_38_7_put;
uint32_t ut_bms_dbg_38_7_put_ctr;
void ut_IlPutTxbms_dbg_38_7(uint8_t val)
{
    ut_bms_dbg_38_7_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxbms_dbg_38_7(val);
    }
    #endif
    ut_bms_dbg_38_7_put = val;
}


uint8_t ut_bms_dbg_38_6_put;
uint32_t ut_bms_dbg_38_6_put_ctr;
void ut_IlPutTxbms_dbg_38_6(uint8_t val)
{
    ut_bms_dbg_38_6_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxbms_dbg_38_6(val);
    }
    #endif
    ut_bms_dbg_38_6_put = val;
}


uint8_t ut_NBMS_05Checksum_put;
uint32_t ut_NBMS_05Checksum_put_ctr;
void ut_IlPutTxNBMS_05Checksum(uint8_t val)
{
    ut_NBMS_05Checksum_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNBMS_05Checksum(val);
    }
    #endif
    ut_NBMS_05Checksum_put = val;
}


uint8_t ut_rLastChargeSOCDelta_put;
uint32_t ut_rLastChargeSOCDelta_put_ctr;
void ut_IlPutTxrLastChargeSOCDelta(uint8_t val)
{
    ut_rLastChargeSOCDelta_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxrLastChargeSOCDelta(val);
    }
    #endif
    ut_rLastChargeSOCDelta_put = val;
}


uint8_t ut_rBatterySOHCPB_put;
uint32_t ut_rBatterySOHCPB_put_ctr;
void ut_IlPutTxrBatterySOHCPB(uint8_t val)
{
    ut_rBatterySOHCPB_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxrBatterySOHCPB(val);
    }
    #endif
    ut_rBatterySOHCPB_put = val;
}


uint8_t ut_rBatterySOC_put;
uint32_t ut_rBatterySOC_put_ctr;
void ut_IlPutTxrBatterySOC(uint8_t val)
{
    ut_rBatterySOC_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxrBatterySOC(val);
    }
    #endif
    ut_rBatterySOC_put = val;
}


uint8_t ut_NBatterySOCDesired_put;
uint32_t ut_NBatterySOCDesired_put_ctr;
void ut_IlPutTxNBatterySOCDesired(uint8_t val)
{
    ut_NBatterySOCDesired_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNBatterySOCDesired(val);
    }
    #endif
    ut_NBatterySOCDesired_put = val;
}


uint8_t ut_NBMSClusterMessage_put;
uint32_t ut_NBMSClusterMessage_put_ctr;
void ut_IlPutTxNBMSClusterMessage(uint8_t val)
{
    ut_NBMSClusterMessage_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNBMSClusterMessage(val);
    }
    #endif
    ut_NBMSClusterMessage_put = val;
}

bool_t ut_NBMSClusterMessageConfirmation;
uint32_t ut_NBMSClusterMessageConfirmation_ctr;
uint8_t ut_IlGetNBMSClusterMessageConfirmation(void)
{
    ut_NBMSClusterMessageConfirmation_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_NBMSClusterMessageConfirmation = IlGetNBMSClusterMessageConfirmation();
    }
    #endif
    return ut_NBMSClusterMessageConfirmation;
}

uint32_t ut_NBMSClusterMessageConfirmation_clr_ctr;
void ut_IlClrNBMSClusterMessageConfirmation(void)
{
    ut_NBMSClusterMessageConfirmation_clr_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlClrNBMSClusterMessageConfirmation();
    }
    #endif
    ut_NBMSClusterMessageConfirmation = FALSE;
}


uint8_t ut_NBMS_05Counter_put;
uint32_t ut_NBMS_05Counter_put_ctr;
void ut_IlPutTxNBMS_05Counter(uint8_t val)
{
    ut_NBMS_05Counter_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNBMS_05Counter(val);
    }
    #endif
    ut_NBMS_05Counter_put = val;
}


uint8_t ut_BBatteryWarrantyVoid_put;
uint32_t ut_BBatteryWarrantyVoid_put_ctr;
void ut_IlPutTxBBatteryWarrantyVoid(uint8_t val)
{
    ut_BBatteryWarrantyVoid_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxBBatteryWarrantyVoid(val);
    }
    #endif
    ut_BBatteryWarrantyVoid_put = val;
}


uint16_t ut_TCellMax_put;
uint32_t ut_TCellMax_put_ctr;
void ut_IlPutTxTCellMax(uint16_t val)
{
    ut_TCellMax_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxTCellMax(val);
    }
    #endif
    ut_TCellMax_put = val;
}


uint8_t ut_rBatterySOHCPC_put;
uint32_t ut_rBatterySOHCPC_put_ctr;
void ut_IlPutTxrBatterySOHCPC(uint8_t val)
{
    ut_rBatterySOHCPC_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxrBatterySOHCPC(val);
    }
    #endif
    ut_rBatterySOHCPC_put = val;
}


uint16_t ut_TCellMin_put;
uint32_t ut_TCellMin_put_ctr;
void ut_IlPutTxTCellMin(uint16_t val)
{
    ut_TCellMin_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxTCellMin(val);
    }
    #endif
    ut_TCellMin_put = val;
}


uint8_t ut_TBMSOutlet_put;
uint32_t ut_TBMSOutlet_put_ctr;
void ut_IlPutTxTBMSOutlet(uint8_t val)
{
    ut_TBMSOutlet_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxTBMSOutlet(val);
    }
    #endif
    ut_TBMSOutlet_put = val;
}


uint8_t ut_NBMS_04Checksum_put;
uint32_t ut_NBMS_04Checksum_put_ctr;
void ut_IlPutTxNBMS_04Checksum(uint8_t val)
{
    ut_NBMS_04Checksum_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNBMS_04Checksum(val);
    }
    #endif
    ut_NBMS_04Checksum_put = val;
}


uint8_t ut_TBMSInlet_put;
uint32_t ut_TBMSInlet_put_ctr;
void ut_IlPutTxTBMSInlet(uint8_t val)
{
    ut_TBMSInlet_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxTBMSInlet(val);
    }
    #endif
    ut_TBMSInlet_put = val;
}


uint8_t ut_BBMSChargerTetheredStatus_put;
uint32_t ut_BBMSChargerTetheredStatus_put_ctr;
void ut_IlPutTxBBMSChargerTetheredStatus(uint8_t val)
{
    ut_BBMSChargerTetheredStatus_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxBBMSChargerTetheredStatus(val);
    }
    #endif
    ut_BBMSChargerTetheredStatus_put = val;
}


uint8_t ut_NBMS_04Counter_put;
uint32_t ut_NBMS_04Counter_put_ctr;
void ut_IlPutTxNBMS_04Counter(uint8_t val)
{
    ut_NBMS_04Counter_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNBMS_04Counter(val);
    }
    #endif
    ut_NBMS_04Counter_put = val;
}


int8_t ut_mad_A_packMovAvgNet_A_put;
uint32_t ut_mad_A_packMovAvgNet_A_put_ctr;
void ut_IlPutTxmad_A_packMovAvgNet_A(int8_t val)
{
    ut_mad_A_packMovAvgNet_A_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxmad_A_packMovAvgNet_A(val);
    }
    #endif
    ut_mad_A_packMovAvgNet_A_put = val;
}


uint16_t ut_hrd_cellSerResEst_Ohm_put;
uint32_t ut_hrd_cellSerResEst_Ohm_put_ctr;
void ut_IlPutTxhrd_cellSerResEst_Ohm(uint16_t val)
{
    ut_hrd_cellSerResEst_Ohm_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxhrd_cellSerResEst_Ohm(val);
    }
    #endif
    ut_hrd_cellSerResEst_Ohm_put = val;
}


uint8_t ut_mad_A_packMovAvgChg_A_put;
uint32_t ut_mad_A_packMovAvgChg_A_put_ctr;
void ut_IlPutTxmad_A_packMovAvgChg_A(uint8_t val)
{
    ut_mad_A_packMovAvgChg_A_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxmad_A_packMovAvgChg_A(val);
    }
    #endif
    ut_mad_A_packMovAvgChg_A_put = val;
}


uint8_t ut_mad_A_packMovAvgDis_A_put;
uint32_t ut_mad_A_packMovAvgDis_A_put_ctr;
void ut_IlPutTxmad_A_packMovAvgDis_A(uint8_t val)
{
    ut_mad_A_packMovAvgDis_A_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxmad_A_packMovAvgDis_A(val);
    }
    #endif
    ut_mad_A_packMovAvgDis_A_put = val;
}


uint16_t ut_dcd_tm_ceRunTime0_put;
uint32_t ut_dcd_tm_ceRunTime0_put_ctr;
void ut_IlPutTxdcd_tm_ceRunTime0(uint16_t val)
{
    ut_dcd_tm_ceRunTime0_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxdcd_tm_ceRunTime0(val);
    }
    #endif
    ut_dcd_tm_ceRunTime0_put = val;
}


int16_t ut_VPackDCLink_put;
uint32_t ut_VPackDCLink_put_ctr;
void ut_IlPutTxVPackDCLink(int16_t val)
{
    ut_VPackDCLink_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxVPackDCLink(val);
    }
    #endif
    ut_VPackDCLink_put = val;
}


uint16_t ut_dcd_tm_socRunTime0_put;
uint32_t ut_dcd_tm_socRunTime0_put_ctr;
void ut_IlPutTxdcd_tm_socRunTime0(uint16_t val)
{
    ut_dcd_tm_socRunTime0_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxdcd_tm_socRunTime0(val);
    }
    #endif
    ut_dcd_tm_socRunTime0_put = val;
}


uint8_t ut_acv_enum_packDisLimReasonFF_Med_put;
uint32_t ut_acv_enum_packDisLimReasonFF_Med_put_ctr;
void ut_IlPutTxacv_enum_packDisLimReasonFF_Med(uint8_t val)
{
    ut_acv_enum_packDisLimReasonFF_Med_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxacv_enum_packDisLimReasonFF_Med(val);
    }
    #endif
    ut_acv_enum_packDisLimReasonFF_Med_put = val;
}


uint8_t ut_acv_enum_packChgLimReasonFF_Med_put;
uint32_t ut_acv_enum_packChgLimReasonFF_Med_put_ctr;
void ut_IlPutTxacv_enum_packChgLimReasonFF_Med(uint8_t val)
{
    ut_acv_enum_packChgLimReasonFF_Med_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxacv_enum_packChgLimReasonFF_Med(val);
    }
    #endif
    ut_acv_enum_packChgLimReasonFF_Med_put = val;
}


uint8_t ut_acv_enum_packDisLimReasonFF_Long_put;
uint32_t ut_acv_enum_packDisLimReasonFF_Long_put_ctr;
void ut_IlPutTxacv_enum_packDisLimReasonFF_Long(uint8_t val)
{
    ut_acv_enum_packDisLimReasonFF_Long_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxacv_enum_packDisLimReasonFF_Long(val);
    }
    #endif
    ut_acv_enum_packDisLimReasonFF_Long_put = val;
}


uint8_t ut_acv_enum_packChgLimReasonFF_Shrt_put;
uint32_t ut_acv_enum_packChgLimReasonFF_Shrt_put_ctr;
void ut_IlPutTxacv_enum_packChgLimReasonFF_Shrt(uint8_t val)
{
    ut_acv_enum_packChgLimReasonFF_Shrt_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxacv_enum_packChgLimReasonFF_Shrt(val);
    }
    #endif
    ut_acv_enum_packChgLimReasonFF_Shrt_put = val;
}


uint8_t ut_acv_enum_packChgLimReasonFF_Long_put;
uint32_t ut_acv_enum_packChgLimReasonFF_Long_put_ctr;
void ut_IlPutTxacv_enum_packChgLimReasonFF_Long(uint8_t val)
{
    ut_acv_enum_packChgLimReasonFF_Long_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxacv_enum_packChgLimReasonFF_Long(val);
    }
    #endif
    ut_acv_enum_packChgLimReasonFF_Long_put = val;
}


uint8_t ut_acv_enum_packDisLimReasonFF_Shrt_put;
uint32_t ut_acv_enum_packDisLimReasonFF_Shrt_put_ctr;
void ut_IlPutTxacv_enum_packDisLimReasonFF_Shrt(uint8_t val)
{
    ut_acv_enum_packDisLimReasonFF_Shrt_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxacv_enum_packDisLimReasonFF_Shrt(val);
    }
    #endif
    ut_acv_enum_packDisLimReasonFF_Shrt_put = val;
}


uint8_t ut_scv_pct_socObvEst_min_put;
uint32_t ut_scv_pct_socObvEst_min_put_ctr;
void ut_IlPutTxscv_pct_socObvEst_min(uint8_t val)
{
    ut_scv_pct_socObvEst_min_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxscv_pct_socObvEst_min(val);
    }
    #endif
    ut_scv_pct_socObvEst_min_put = val;
}


uint8_t ut_cev_pct_cellVSOCEst_min_put;
uint32_t ut_cev_pct_cellVSOCEst_min_put_ctr;
void ut_IlPutTxcev_pct_cellVSOCEst_min(uint8_t val)
{
    ut_cev_pct_cellVSOCEst_min_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxcev_pct_cellVSOCEst_min(val);
    }
    #endif
    ut_cev_pct_cellVSOCEst_min_put = val;
}


uint8_t ut_cev_pct_cellVSOCEst_max_put;
uint32_t ut_cev_pct_cellVSOCEst_max_put_ctr;
void ut_IlPutTxcev_pct_cellVSOCEst_max(uint8_t val)
{
    ut_cev_pct_cellVSOCEst_max_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxcev_pct_cellVSOCEst_max(val);
    }
    #endif
    ut_cev_pct_cellVSOCEst_max_put = val;
}


uint8_t ut_scv_pct_socObvEst_max_put;
uint32_t ut_scv_pct_socObvEst_max_put_ctr;
void ut_IlPutTxscv_pct_socObvEst_max(uint8_t val)
{
    ut_scv_pct_socObvEst_max_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxscv_pct_socObvEst_max(val);
    }
    #endif
    ut_scv_pct_socObvEst_max_put = val;
}


uint8_t ut_ccv_pct_cellSOC_max_put;
uint32_t ut_ccv_pct_cellSOC_max_put_ctr;
void ut_IlPutTxccv_pct_cellSOC_max(uint8_t val)
{
    ut_ccv_pct_cellSOC_max_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxccv_pct_cellSOC_max(val);
    }
    #endif
    ut_ccv_pct_cellSOC_max_put = val;
}


uint8_t ut_ccv_pct_cellSOC_min_put;
uint32_t ut_ccv_pct_cellSOC_min_put_ctr;
void ut_IlPutTxccv_pct_cellSOC_min(uint8_t val)
{
    ut_ccv_pct_cellSOC_min_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxccv_pct_cellSOC_min(val);
    }
    #endif
    ut_ccv_pct_cellSOC_min_put = val;
}


int8_t ut_tmv_t_cellCoreModel_dC_min_put;
uint32_t ut_tmv_t_cellCoreModel_dC_min_put_ctr;
void ut_IlPutTxtmv_t_cellCoreModel_dC_min(int8_t val)
{
    ut_tmv_t_cellCoreModel_dC_min_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxtmv_t_cellCoreModel_dC_min(val);
    }
    #endif
    ut_tmv_t_cellCoreModel_dC_min_put = val;
}


int8_t ut_tmv_t_cellCoreModel_dC_max_put;
uint32_t ut_tmv_t_cellCoreModel_dC_max_put_ctr;
void ut_IlPutTxtmv_t_cellCoreModel_dC_max(int8_t val)
{
    ut_tmv_t_cellCoreModel_dC_max_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxtmv_t_cellCoreModel_dC_max(val);
    }
    #endif
    ut_tmv_t_cellCoreModel_dC_max_put = val;
}


uint16_t ut_PDischargeMaxShortTerm_put;
uint32_t ut_PDischargeMaxShortTerm_put_ctr;
void ut_IlPutTxPDischargeMaxShortTerm(uint16_t val)
{
    ut_PDischargeMaxShortTerm_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxPDischargeMaxShortTerm(val);
    }
    #endif
    ut_PDischargeMaxShortTerm_put = val;
}


uint8_t ut_NBMS_01Counter_put;
uint32_t ut_NBMS_01Counter_put_ctr;
void ut_IlPutTxNBMS_01Counter(uint8_t val)
{
    ut_NBMS_01Counter_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNBMS_01Counter(val);
    }
    #endif
    ut_NBMS_01Counter_put = val;
}


uint16_t ut_IDischargeMaxShortTerm_put;
uint32_t ut_IDischargeMaxShortTerm_put_ctr;
void ut_IlPutTxIDischargeMaxShortTerm(uint16_t val)
{
    ut_IDischargeMaxShortTerm_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxIDischargeMaxShortTerm(val);
    }
    #endif
    ut_IDischargeMaxShortTerm_put = val;
}


uint8_t ut_NBMS_01Checksum_put;
uint32_t ut_NBMS_01Checksum_put_ctr;
void ut_IlPutTxNBMS_01Checksum(uint8_t val)
{
    ut_NBMS_01Checksum_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNBMS_01Checksum(val);
    }
    #endif
    ut_NBMS_01Checksum_put = val;
}


uint16_t ut_tChargingRemainingDisplayed_put;
uint32_t ut_tChargingRemainingDisplayed_put_ctr;
void ut_IlPutTxtChargingRemainingDisplayed(uint16_t val)
{
    ut_tChargingRemainingDisplayed_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxtChargingRemainingDisplayed(val);
    }
    #endif
    ut_tChargingRemainingDisplayed_put = val;
}


uint16_t ut_VHybridBattery_put;
uint32_t ut_VHybridBattery_put_ctr;
void ut_IlPutTxVHybridBattery(uint16_t val)
{
    ut_VHybridBattery_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxVHybridBattery(val);
    }
    #endif
    ut_VHybridBattery_put = val;
}


uint8_t ut_NBMS_00Counter_put;
uint32_t ut_NBMS_00Counter_put_ctr;
void ut_IlPutTxNBMS_00Counter(uint8_t val)
{
    ut_NBMS_00Counter_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNBMS_00Counter(val);
    }
    #endif
    ut_NBMS_00Counter_put = val;
}


uint16_t ut_IActual_put;
uint32_t ut_IActual_put_ctr;
void ut_IlPutTxIActual(uint16_t val)
{
    ut_IActual_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxIActual(val);
    }
    #endif
    ut_IActual_put = val;
}


uint8_t ut_NBMS_00Checksum_put;
uint32_t ut_NBMS_00Checksum_put_ctr;
void ut_IlPutTxNBMS_00Checksum(uint8_t val)
{
    ut_NBMS_00Checksum_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNBMS_00Checksum(val);
    }
    #endif
    ut_NBMS_00Checksum_put = val;
}


uint16_t ut_PActual_put;
uint32_t ut_PActual_put_ctr;
void ut_IlPutTxPActual(uint16_t val)
{
    ut_PActual_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxPActual(val);
    }
    #endif
    ut_PActual_put = val;
}


uint16_t ut_PDischargeMaxLongTerm_put;
uint32_t ut_PDischargeMaxLongTerm_put_ctr;
void ut_IlPutTxPDischargeMaxLongTerm(uint16_t val)
{
    ut_PDischargeMaxLongTerm_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxPDischargeMaxLongTerm(val);
    }
    #endif
    ut_PDischargeMaxLongTerm_put = val;
}


uint8_t ut_NBMS_08Counter_put;
uint32_t ut_NBMS_08Counter_put_ctr;
void ut_IlPutTxNBMS_08Counter(uint8_t val)
{
    ut_NBMS_08Counter_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNBMS_08Counter(val);
    }
    #endif
    ut_NBMS_08Counter_put = val;
}


uint8_t ut_NBMS_08Checksum_put;
uint32_t ut_NBMS_08Checksum_put_ctr;
void ut_IlPutTxNBMS_08Checksum(uint8_t val)
{
    ut_NBMS_08Checksum_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNBMS_08Checksum(val);
    }
    #endif
    ut_NBMS_08Checksum_put = val;
}


uint16_t ut_IDischargeMaxLongTerm_put;
uint32_t ut_IDischargeMaxLongTerm_put_ctr;
void ut_IlPutTxIDischargeMaxLongTerm(uint16_t val)
{
    ut_IDischargeMaxLongTerm_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxIDischargeMaxLongTerm(val);
    }
    #endif
    ut_IDischargeMaxLongTerm_put = val;
}


uint16_t ut_PChargeMaxLongTerm_put;
uint32_t ut_PChargeMaxLongTerm_put_ctr;
void ut_IlPutTxPChargeMaxLongTerm(uint16_t val)
{
    ut_PChargeMaxLongTerm_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxPChargeMaxLongTerm(val);
    }
    #endif
    ut_PChargeMaxLongTerm_put = val;
}


uint8_t ut_NBMS_09Checksum_put;
uint32_t ut_NBMS_09Checksum_put_ctr;
void ut_IlPutTxNBMS_09Checksum(uint8_t val)
{
    ut_NBMS_09Checksum_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNBMS_09Checksum(val);
    }
    #endif
    ut_NBMS_09Checksum_put = val;
}


uint8_t ut_NBMS_09Counter_put;
uint32_t ut_NBMS_09Counter_put_ctr;
void ut_IlPutTxNBMS_09Counter(uint8_t val)
{
    ut_NBMS_09Counter_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNBMS_09Counter(val);
    }
    #endif
    ut_NBMS_09Counter_put = val;
}


uint16_t ut_IChargeMaxLongTerm_put;
uint32_t ut_IChargeMaxLongTerm_put_ctr;
void ut_IlPutTxIChargeMaxLongTerm(uint16_t val)
{
    ut_IChargeMaxLongTerm_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxIChargeMaxLongTerm(val);
    }
    #endif
    ut_IChargeMaxLongTerm_put = val;
}


uint16_t ut_PDischargeMaxMediumTerm_put;
uint32_t ut_PDischargeMaxMediumTerm_put_ctr;
void ut_IlPutTxPDischargeMaxMediumTerm(uint16_t val)
{
    ut_PDischargeMaxMediumTerm_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxPDischargeMaxMediumTerm(val);
    }
    #endif
    ut_PDischargeMaxMediumTerm_put = val;
}


uint8_t ut_NBMS_06Checksum_put;
uint32_t ut_NBMS_06Checksum_put_ctr;
void ut_IlPutTxNBMS_06Checksum(uint8_t val)
{
    ut_NBMS_06Checksum_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNBMS_06Checksum(val);
    }
    #endif
    ut_NBMS_06Checksum_put = val;
}


uint16_t ut_IDischargeMaxMediumTerm_put;
uint32_t ut_IDischargeMaxMediumTerm_put_ctr;
void ut_IlPutTxIDischargeMaxMediumTerm(uint16_t val)
{
    ut_IDischargeMaxMediumTerm_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxIDischargeMaxMediumTerm(val);
    }
    #endif
    ut_IDischargeMaxMediumTerm_put = val;
}


uint8_t ut_NBMS_06Counter_put;
uint32_t ut_NBMS_06Counter_put_ctr;
void ut_IlPutTxNBMS_06Counter(uint8_t val)
{
    ut_NBMS_06Counter_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNBMS_06Counter(val);
    }
    #endif
    ut_NBMS_06Counter_put = val;
}


uint8_t ut_NBMS_07Checksum_put;
uint32_t ut_NBMS_07Checksum_put_ctr;
void ut_IlPutTxNBMS_07Checksum(uint8_t val)
{
    ut_NBMS_07Checksum_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNBMS_07Checksum(val);
    }
    #endif
    ut_NBMS_07Checksum_put = val;
}


uint16_t ut_PChargeMaxMediumTerm_put;
uint32_t ut_PChargeMaxMediumTerm_put_ctr;
void ut_IlPutTxPChargeMaxMediumTerm(uint16_t val)
{
    ut_PChargeMaxMediumTerm_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxPChargeMaxMediumTerm(val);
    }
    #endif
    ut_PChargeMaxMediumTerm_put = val;
}


uint16_t ut_IChargeMaxMediumTerm_put;
uint32_t ut_IChargeMaxMediumTerm_put_ctr;
void ut_IlPutTxIChargeMaxMediumTerm(uint16_t val)
{
    ut_IChargeMaxMediumTerm_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxIChargeMaxMediumTerm(val);
    }
    #endif
    ut_IChargeMaxMediumTerm_put = val;
}


uint8_t ut_NBMS_07Counter_put;
uint32_t ut_NBMS_07Counter_put_ctr;
void ut_IlPutTxNBMS_07Counter(uint8_t val)
{
    ut_NBMS_07Counter_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNBMS_07Counter(val);
    }
    #endif
    ut_NBMS_07Counter_put = val;
}


uint8_t ut_NBMSStatus_put;
uint32_t ut_NBMSStatus_put_ctr;
void ut_IlPutTxNBMSStatus(uint8_t val)
{
    ut_NBMSStatus_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNBMSStatus(val);
    }
    #endif
    ut_NBMSStatus_put = val;
}


uint8_t ut_BPrechargeContactorState_put;
uint32_t ut_BPrechargeContactorState_put_ctr;
void ut_IlPutTxBPrechargeContactorState(uint8_t val)
{
    ut_BPrechargeContactorState_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxBPrechargeContactorState(val);
    }
    #endif
    ut_BPrechargeContactorState_put = val;
}


uint8_t ut_NBMSMILRequested_put;
uint32_t ut_NBMSMILRequested_put_ctr;
void ut_IlPutTxNBMSMILRequested(uint8_t val)
{
    ut_NBMSMILRequested_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNBMSMILRequested(val);
    }
    #endif
    ut_NBMSMILRequested_put = val;
}


uint8_t ut_BBMSContactorOpenIndicator_put;
uint32_t ut_BBMSContactorOpenIndicator_put_ctr;
void ut_IlPutTxBBMSContactorOpenIndicator(uint8_t val)
{
    ut_BBMSContactorOpenIndicator_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxBBMSContactorOpenIndicator(val);
    }
    #endif
    ut_BBMSContactorOpenIndicator_put = val;
}


uint8_t ut_BContactorStuckOpen_put;
uint32_t ut_BContactorStuckOpen_put_ctr;
void ut_IlPutTxBContactorStuckOpen(uint8_t val)
{
    ut_BContactorStuckOpen_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxBContactorStuckOpen(val);
    }
    #endif
    ut_BContactorStuckOpen_put = val;
}


uint8_t ut_NHVBSoCResetState_put;
uint32_t ut_NHVBSoCResetState_put_ctr;
void ut_IlPutTxNHVBSoCResetState(uint8_t val)
{
    ut_NHVBSoCResetState_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNHVBSoCResetState(val);
    }
    #endif
    ut_NHVBSoCResetState_put = val;
}


uint8_t ut_BContactorStuckClosed_put;
uint32_t ut_BContactorStuckClosed_put_ctr;
void ut_IlPutTxBContactorStuckClosed(uint8_t val)
{
    ut_BContactorStuckClosed_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxBContactorStuckClosed(val);
    }
    #endif
    ut_BContactorStuckClosed_put = val;
}


uint8_t ut_BBMSContactorCloseIndicator_put;
uint32_t ut_BBMSContactorCloseIndicator_put_ctr;
void ut_IlPutTxBBMSContactorCloseIndicator(uint8_t val)
{
    ut_BBMSContactorCloseIndicator_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxBBMSContactorCloseIndicator(val);
    }
    #endif
    ut_BBMSContactorCloseIndicator_put = val;
}


uint8_t ut_NBMS_03Counter_put;
uint32_t ut_NBMS_03Counter_put_ctr;
void ut_IlPutTxNBMS_03Counter(uint8_t val)
{
    ut_NBMS_03Counter_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNBMS_03Counter(val);
    }
    #endif
    ut_NBMS_03Counter_put = val;
}


uint8_t ut_NBMS_03Checksum_put;
uint32_t ut_NBMS_03Checksum_put_ctr;
void ut_IlPutTxNBMS_03Checksum(uint8_t val)
{
    ut_NBMS_03Checksum_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNBMS_03Checksum(val);
    }
    #endif
    ut_NBMS_03Checksum_put = val;
}


uint8_t ut_BChargerNegContactorState_put;
uint32_t ut_BChargerNegContactorState_put_ctr;
void ut_IlPutTxBChargerNegContactorState(uint8_t val)
{
    ut_BChargerNegContactorState_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxBChargerNegContactorState(val);
    }
    #endif
    ut_BChargerNegContactorState_put = val;
}


uint8_t ut_NFullDischargeRequested_put;
uint32_t ut_NFullDischargeRequested_put_ctr;
void ut_IlPutTxNFullDischargeRequested(uint8_t val)
{
    ut_NFullDischargeRequested_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNFullDischargeRequested(val);
    }
    #endif
    ut_NFullDischargeRequested_put = val;
}


uint8_t ut_BVehicleNegContactorState_put;
uint32_t ut_BVehicleNegContactorState_put_ctr;
void ut_IlPutTxBVehicleNegContactorState(uint8_t val)
{
    ut_BVehicleNegContactorState_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxBVehicleNegContactorState(val);
    }
    #endif
    ut_BVehicleNegContactorState_put = val;
}


uint8_t ut_BChargerPosContactorState_put;
uint32_t ut_BChargerPosContactorState_put_ctr;
void ut_IlPutTxBChargerPosContactorState(uint8_t val)
{
    ut_BChargerPosContactorState_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxBChargerPosContactorState(val);
    }
    #endif
    ut_BChargerPosContactorState_put = val;
}


uint8_t ut_BVehiclePosContactorState_put;
uint32_t ut_BVehiclePosContactorState_put_ctr;
void ut_IlPutTxBVehiclePosContactorState(uint8_t val)
{
    ut_BVehiclePosContactorState_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxBVehiclePosContactorState(val);
    }
    #endif
    ut_BVehiclePosContactorState_put = val;
}


uint16_t ut_IChargeMaxShortTerm_put;
uint32_t ut_IChargeMaxShortTerm_put_ctr;
void ut_IlPutTxIChargeMaxShortTerm(uint16_t val)
{
    ut_IChargeMaxShortTerm_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxIChargeMaxShortTerm(val);
    }
    #endif
    ut_IChargeMaxShortTerm_put = val;
}


uint8_t ut_NBMS_02Counter_put;
uint32_t ut_NBMS_02Counter_put_ctr;
void ut_IlPutTxNBMS_02Counter(uint8_t val)
{
    ut_NBMS_02Counter_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNBMS_02Counter(val);
    }
    #endif
    ut_NBMS_02Counter_put = val;
}


uint16_t ut_PChargeMaxShortTerm_put;
uint32_t ut_PChargeMaxShortTerm_put_ctr;
void ut_IlPutTxPChargeMaxShortTerm(uint16_t val)
{
    ut_PChargeMaxShortTerm_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxPChargeMaxShortTerm(val);
    }
    #endif
    ut_PChargeMaxShortTerm_put = val;
}


uint8_t ut_NBMS_02Checksum_put;
uint32_t ut_NBMS_02Checksum_put_ctr;
void ut_IlPutTxNBMS_02Checksum(uint8_t val)
{
    ut_NBMS_02Checksum_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNBMS_02Checksum(val);
    }
    #endif
    ut_NBMS_02Checksum_put = val;
}


/* Rx groups source start */
/* Tx groups source start */
/* Rx signals source start */
uint8_t ut_ISA_Fourth_status_get;
uint32_t ut_ISA_Fourth_status_get_ctr;
uint8_t ut_IlGetRxISA_Fourth_status(void)
{
    ut_ISA_Fourth_status_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_ISA_Fourth_status_get = IlGetRxISA_Fourth_status();
    }
    #endif
    return ut_ISA_Fourth_status_get;
}


uint8_t ut_ISA_Response_ID_get;
uint32_t ut_ISA_Response_ID_get_ctr;
uint8_t ut_IlGetRxISA_Response_ID(void)
{
    ut_ISA_Response_ID_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_ISA_Response_ID_get = IlGetRxISA_Response_ID();
    }
    #endif
    return ut_ISA_Response_ID_get;
}


uint8_t ut_ISA_Response_DB1_get;
uint32_t ut_ISA_Response_DB1_get_ctr;
uint8_t ut_IlGetRxISA_Response_DB1(void)
{
    ut_ISA_Response_DB1_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_ISA_Response_DB1_get = IlGetRxISA_Response_DB1();
    }
    #endif
    return ut_ISA_Response_DB1_get;
}


uint8_t ut_ISA_Response_DB2_get;
uint32_t ut_ISA_Response_DB2_get_ctr;
uint8_t ut_IlGetRxISA_Response_DB2(void)
{
    ut_ISA_Response_DB2_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_ISA_Response_DB2_get = IlGetRxISA_Response_DB2();
    }
    #endif
    return ut_ISA_Response_DB2_get;
}


uint8_t ut_ISA_Response_DB3_get;
uint32_t ut_ISA_Response_DB3_get_ctr;
uint8_t ut_IlGetRxISA_Response_DB3(void)
{
    ut_ISA_Response_DB3_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_ISA_Response_DB3_get = IlGetRxISA_Response_DB3();
    }
    #endif
    return ut_ISA_Response_DB3_get;
}


uint8_t ut_ISA_Response_DB4_get;
uint32_t ut_ISA_Response_DB4_get_ctr;
uint8_t ut_IlGetRxISA_Response_DB4(void)
{
    ut_ISA_Response_DB4_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_ISA_Response_DB4_get = IlGetRxISA_Response_DB4();
    }
    #endif
    return ut_ISA_Response_DB4_get;
}


uint8_t ut_ISA_Response_DB5_get;
uint32_t ut_ISA_Response_DB5_get_ctr;
uint8_t ut_IlGetRxISA_Response_DB5(void)
{
    ut_ISA_Response_DB5_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_ISA_Response_DB5_get = IlGetRxISA_Response_DB5();
    }
    #endif
    return ut_ISA_Response_DB5_get;
}


uint8_t ut_ISA_First_status_get;
uint32_t ut_ISA_First_status_get_ctr;
uint8_t ut_IlGetRxISA_First_status(void)
{
    ut_ISA_First_status_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_ISA_First_status_get = IlGetRxISA_First_status();
    }
    #endif
    return ut_ISA_First_status_get;
}


uint8_t ut_ISA_Response_DB7_get;
uint32_t ut_ISA_Response_DB7_get_ctr;
uint8_t ut_IlGetRxISA_Response_DB7(void)
{
    ut_ISA_Response_DB7_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_ISA_Response_DB7_get = IlGetRxISA_Response_DB7();
    }
    #endif
    return ut_ISA_Response_DB7_get;
}


uint8_t ut_ISA_Second_status_get;
uint32_t ut_ISA_Second_status_get_ctr;
uint8_t ut_IlGetRxISA_Second_status(void)
{
    ut_ISA_Second_status_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_ISA_Second_status_get = IlGetRxISA_Second_status();
    }
    #endif
    return ut_ISA_Second_status_get;
}


uint8_t ut_ISA_Third_type_get;
uint32_t ut_ISA_Third_type_get_ctr;
uint8_t ut_IlGetRxISA_Third_type(void)
{
    ut_ISA_Third_type_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_ISA_Third_type_get = IlGetRxISA_Third_type();
    }
    #endif
    return ut_ISA_Third_type_get;
}


uint8_t ut_ISA_Third_status_get;
uint32_t ut_ISA_Third_status_get_ctr;
uint8_t ut_IlGetRxISA_Third_status(void)
{
    ut_ISA_Third_status_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_ISA_Third_status_get = IlGetRxISA_Third_status();
    }
    #endif
    return ut_ISA_Third_status_get;
}


int32_t ut_ISA_Third_result_get;
uint32_t ut_ISA_Third_result_get_ctr;
int32_t ut_IlGetRxISA_Third_result(void)
{
    ut_ISA_Third_result_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_ISA_Third_result_get = IlGetRxISA_Third_result();
    }
    #endif
    return ut_ISA_Third_result_get;
}


uint8_t ut_ISA_Response_DB6_get;
uint32_t ut_ISA_Response_DB6_get_ctr;
uint8_t ut_IlGetRxISA_Response_DB6(void)
{
    ut_ISA_Response_DB6_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_ISA_Response_DB6_get = IlGetRxISA_Response_DB6();
    }
    #endif
    return ut_ISA_Response_DB6_get;
}


uint8_t ut_ISA_Second_type_get;
uint32_t ut_ISA_Second_type_get_ctr;
uint8_t ut_IlGetRxISA_Second_type(void)
{
    ut_ISA_Second_type_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_ISA_Second_type_get = IlGetRxISA_Second_type();
    }
    #endif
    return ut_ISA_Second_type_get;
}


int32_t ut_ISA_Fifth_result_get;
uint32_t ut_ISA_Fifth_result_get_ctr;
int32_t ut_IlGetRxISA_Fifth_result(void)
{
    ut_ISA_Fifth_result_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_ISA_Fifth_result_get = IlGetRxISA_Fifth_result();
    }
    #endif
    return ut_ISA_Fifth_result_get;
}


uint8_t ut_ISA_Fifth_type_get;
uint32_t ut_ISA_Fifth_type_get_ctr;
uint8_t ut_IlGetRxISA_Fifth_type(void)
{
    ut_ISA_Fifth_type_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_ISA_Fifth_type_get = IlGetRxISA_Fifth_type();
    }
    #endif
    return ut_ISA_Fifth_type_get;
}


uint8_t ut_ISA_Sixth_status_get;
uint32_t ut_ISA_Sixth_status_get_ctr;
uint8_t ut_IlGetRxISA_Sixth_status(void)
{
    ut_ISA_Sixth_status_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_ISA_Sixth_status_get = IlGetRxISA_Sixth_status();
    }
    #endif
    return ut_ISA_Sixth_status_get;
}


uint8_t ut_ISA_Sixth_type_get;
uint32_t ut_ISA_Sixth_type_get_ctr;
uint8_t ut_IlGetRxISA_Sixth_type(void)
{
    ut_ISA_Sixth_type_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_ISA_Sixth_type_get = IlGetRxISA_Sixth_type();
    }
    #endif
    return ut_ISA_Sixth_type_get;
}


int32_t ut_ISA_Sixth_result_get;
uint32_t ut_ISA_Sixth_result_get_ctr;
int32_t ut_IlGetRxISA_Sixth_result(void)
{
    ut_ISA_Sixth_result_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_ISA_Sixth_result_get = IlGetRxISA_Sixth_result();
    }
    #endif
    return ut_ISA_Sixth_result_get;
}


uint8_t ut_ISA_Fifth_status_get;
uint32_t ut_ISA_Fifth_status_get_ctr;
uint8_t ut_IlGetRxISA_Fifth_status(void)
{
    ut_ISA_Fifth_status_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_ISA_Fifth_status_get = IlGetRxISA_Fifth_status();
    }
    #endif
    return ut_ISA_Fifth_status_get;
}


int32_t ut_ISA_Fourth_result_get;
uint32_t ut_ISA_Fourth_result_get_ctr;
int32_t ut_IlGetRxISA_Fourth_result(void)
{
    ut_ISA_Fourth_result_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_ISA_Fourth_result_get = IlGetRxISA_Fourth_result();
    }
    #endif
    return ut_ISA_Fourth_result_get;
}


uint8_t ut_ISA_First_type_get;
uint32_t ut_ISA_First_type_get_ctr;
uint8_t ut_IlGetRxISA_First_type(void)
{
    ut_ISA_First_type_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_ISA_First_type_get = IlGetRxISA_First_type();
    }
    #endif
    return ut_ISA_First_type_get;
}


uint8_t ut_ISA_Fourth_type_get;
uint32_t ut_ISA_Fourth_type_get_ctr;
uint8_t ut_IlGetRxISA_Fourth_type(void)
{
    ut_ISA_Fourth_type_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_ISA_Fourth_type_get = IlGetRxISA_Fourth_type();
    }
    #endif
    return ut_ISA_Fourth_type_get;
}


int32_t ut_ISA_Second_result_get;
uint32_t ut_ISA_Second_result_get_ctr;
int32_t ut_IlGetRxISA_Second_result(void)
{
    ut_ISA_Second_result_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_ISA_Second_result_get = IlGetRxISA_Second_result();
    }
    #endif
    return ut_ISA_Second_result_get;
}


int32_t ut_ISA_First_result_get;
uint32_t ut_ISA_First_result_get_ctr;
int32_t ut_IlGetRxISA_First_result(void)
{
    ut_ISA_First_result_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_ISA_First_result_get = IlGetRxISA_First_result();
    }
    #endif
    return ut_ISA_First_result_get;
}


/* Tx signals source start */
uint8_t ut_ISA_Cmd_DB4_put;
uint32_t ut_ISA_Cmd_DB4_put_ctr;
void ut_IlPutTxISA_Cmd_DB4(uint8_t val)
{
    ut_ISA_Cmd_DB4_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxISA_Cmd_DB4(val);
    }
    #endif
    ut_ISA_Cmd_DB4_put = val;
}


uint8_t ut_ISA_Cmd_DB5_put;
uint32_t ut_ISA_Cmd_DB5_put_ctr;
void ut_IlPutTxISA_Cmd_DB5(uint8_t val)
{
    ut_ISA_Cmd_DB5_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxISA_Cmd_DB5(val);
    }
    #endif
    ut_ISA_Cmd_DB5_put = val;
}


uint8_t ut_ISA_Cmd_DB6_put;
uint32_t ut_ISA_Cmd_DB6_put_ctr;
void ut_IlPutTxISA_Cmd_DB6(uint8_t val)
{
    ut_ISA_Cmd_DB6_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxISA_Cmd_DB6(val);
    }
    #endif
    ut_ISA_Cmd_DB6_put = val;
}


uint8_t ut_ISA_Cmd_DB7_put;
uint32_t ut_ISA_Cmd_DB7_put_ctr;
void ut_IlPutTxISA_Cmd_DB7(uint8_t val)
{
    ut_ISA_Cmd_DB7_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxISA_Cmd_DB7(val);
    }
    #endif
    ut_ISA_Cmd_DB7_put = val;
}


uint8_t ut_ISA_Cmd_DB1_put;
uint32_t ut_ISA_Cmd_DB1_put_ctr;
void ut_IlPutTxISA_Cmd_DB1(uint8_t val)
{
    ut_ISA_Cmd_DB1_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxISA_Cmd_DB1(val);
    }
    #endif
    ut_ISA_Cmd_DB1_put = val;
}


uint8_t ut_ISA_Cmd_DB2_put;
uint32_t ut_ISA_Cmd_DB2_put_ctr;
void ut_IlPutTxISA_Cmd_DB2(uint8_t val)
{
    ut_ISA_Cmd_DB2_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxISA_Cmd_DB2(val);
    }
    #endif
    ut_ISA_Cmd_DB2_put = val;
}


uint8_t ut_ISA_Cmd_DB3_put;
uint32_t ut_ISA_Cmd_DB3_put_ctr;
void ut_IlPutTxISA_Cmd_DB3(uint8_t val)
{
    ut_ISA_Cmd_DB3_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxISA_Cmd_DB3(val);
    }
    #endif
    ut_ISA_Cmd_DB3_put = val;
}


uint8_t ut_ISA_Command_ID_put;
uint32_t ut_ISA_Command_ID_put_ctr;
void ut_IlPutTxISA_Command_ID(uint8_t val)
{
    ut_ISA_Command_ID_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxISA_Command_ID(val);
    }
    #endif
    ut_ISA_Command_ID_put = val;
}


/* Rx groups source start */
uint32_t ut_sixth_grp_get_ctr;
void ut_IlGetRxsixth_grp(void)
{
    ut_sixth_grp_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlGetRxsixth_grp();
    }
    #endif
    return;
}

bool_t ut_sixth_grpIndication;
uint32_t ut_sixth_grpIndication_ctr;
uint8_t ut_IlGetsixth_grpIndication(void)
{
    ut_sixth_grpIndication_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_sixth_grpIndication = IlGetsixth_grpIndication();
    }
    #endif
    return ut_sixth_grpIndication;
}

uint32_t ut_sixth_grpIndication_clr_ctr;
void ut_IlClrsixth_grpIndication(void)
{
    ut_sixth_grpIndication_clr_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlClrsixth_grpIndication();
    }
    #endif
    ut_sixth_grpIndication = FALSE;
}


uint32_t ut_fifth_grp_get_ctr;
void ut_IlGetRxfifth_grp(void)
{
    ut_fifth_grp_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlGetRxfifth_grp();
    }
    #endif
    return;
}

bool_t ut_fifth_grpIndication;
uint32_t ut_fifth_grpIndication_ctr;
uint8_t ut_IlGetfifth_grpIndication(void)
{
    ut_fifth_grpIndication_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_fifth_grpIndication = IlGetfifth_grpIndication();
    }
    #endif
    return ut_fifth_grpIndication;
}

uint32_t ut_fifth_grpIndication_clr_ctr;
void ut_IlClrfifth_grpIndication(void)
{
    ut_fifth_grpIndication_clr_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlClrfifth_grpIndication();
    }
    #endif
    ut_fifth_grpIndication = FALSE;
}


uint32_t ut_third_grp_get_ctr;
void ut_IlGetRxthird_grp(void)
{
    ut_third_grp_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlGetRxthird_grp();
    }
    #endif
    return;
}

bool_t ut_third_grpIndication;
uint32_t ut_third_grpIndication_ctr;
uint8_t ut_IlGetthird_grpIndication(void)
{
    ut_third_grpIndication_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_third_grpIndication = IlGetthird_grpIndication();
    }
    #endif
    return ut_third_grpIndication;
}

uint32_t ut_third_grpIndication_clr_ctr;
void ut_IlClrthird_grpIndication(void)
{
    ut_third_grpIndication_clr_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlClrthird_grpIndication();
    }
    #endif
    ut_third_grpIndication = FALSE;
}


uint32_t ut_fourth_grp_get_ctr;
void ut_IlGetRxfourth_grp(void)
{
    ut_fourth_grp_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlGetRxfourth_grp();
    }
    #endif
    return;
}

bool_t ut_fourth_grpIndication;
uint32_t ut_fourth_grpIndication_ctr;
uint8_t ut_IlGetfourth_grpIndication(void)
{
    ut_fourth_grpIndication_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_fourth_grpIndication = IlGetfourth_grpIndication();
    }
    #endif
    return ut_fourth_grpIndication;
}

uint32_t ut_fourth_grpIndication_clr_ctr;
void ut_IlClrfourth_grpIndication(void)
{
    ut_fourth_grpIndication_clr_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlClrfourth_grpIndication();
    }
    #endif
    ut_fourth_grpIndication = FALSE;
}


uint32_t ut_second_grp_get_ctr;
void ut_IlGetRxsecond_grp(void)
{
    ut_second_grp_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlGetRxsecond_grp();
    }
    #endif
    return;
}

bool_t ut_second_grpIndication;
uint32_t ut_second_grpIndication_ctr;
uint8_t ut_IlGetsecond_grpIndication(void)
{
    ut_second_grpIndication_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_second_grpIndication = IlGetsecond_grpIndication();
    }
    #endif
    return ut_second_grpIndication;
}

uint32_t ut_second_grpIndication_clr_ctr;
void ut_IlClrsecond_grpIndication(void)
{
    ut_second_grpIndication_clr_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlClrsecond_grpIndication();
    }
    #endif
    ut_second_grpIndication = FALSE;
}


uint32_t ut_first_grp_get_ctr;
void ut_IlGetRxfirst_grp(void)
{
    ut_first_grp_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlGetRxfirst_grp();
    }
    #endif
    return;
}

bool_t ut_first_grpIndication;
uint32_t ut_first_grpIndication_ctr;
uint8_t ut_IlGetfirst_grpIndication(void)
{
    ut_first_grpIndication_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_first_grpIndication = IlGetfirst_grpIndication();
    }
    #endif
    return ut_first_grpIndication;
}

uint32_t ut_first_grpIndication_clr_ctr;
void ut_IlClrfirst_grpIndication(void)
{
    ut_first_grpIndication_clr_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlClrfirst_grpIndication();
    }
    #endif
    ut_first_grpIndication = FALSE;
}


uint32_t ut_response_grp_get_ctr;
void ut_IlGetRxresponse_grp(void)
{
    ut_response_grp_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlGetRxresponse_grp();
    }
    #endif
    return;
}

bool_t ut_response_grpIndication;
uint32_t ut_response_grpIndication_ctr;
uint8_t ut_IlGetresponse_grpIndication(void)
{
    ut_response_grpIndication_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_response_grpIndication = IlGetresponse_grpIndication();
    }
    #endif
    return ut_response_grpIndication;
}

uint32_t ut_response_grpIndication_clr_ctr;
void ut_IlClrresponse_grpIndication(void)
{
    ut_response_grpIndication_clr_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlClrresponse_grpIndication();
    }
    #endif
    ut_response_grpIndication = FALSE;
}


/* Tx groups source start */
uint32_t ut_Command_grp_put_ctr;
void ut_IlPutTxCommand_grp(void)
{
    ut_Command_grp_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxCommand_grp();
    }
    #endif
    return;
}


/* Rx signals source start */
uint8_t ut_BChargerCableFault_get;
uint32_t ut_BChargerCableFault_get_ctr;
uint8_t ut_IlGetRxBChargerCableFault(void)
{
    ut_BChargerCableFault_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_BChargerCableFault_get = IlGetRxBChargerCableFault();
    }
    #endif
    return ut_BChargerCableFault_get;
}


uint8_t ut_NCharger12VSupplyStatus_get;
uint32_t ut_NCharger12VSupplyStatus_get_ctr;
uint8_t ut_IlGetRxNCharger12VSupplyStatus(void)
{
    ut_NCharger12VSupplyStatus_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_NCharger12VSupplyStatus_get = IlGetRxNCharger12VSupplyStatus();
    }
    #endif
    return ut_NCharger12VSupplyStatus_get;
}


uint8_t ut_NOBC_1Counter_get;
uint32_t ut_NOBC_1Counter_get_ctr;
uint8_t ut_IlGetRxNOBC_1Counter(void)
{
    ut_NOBC_1Counter_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_NOBC_1Counter_get = IlGetRxNOBC_1Counter();
    }
    #endif
    return ut_NOBC_1Counter_get;
}


uint8_t ut_IChargerMax_get;
uint32_t ut_IChargerMax_get_ctr;
uint8_t ut_IlGetRxIChargerMax(void)
{
    ut_IChargerMax_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_IChargerMax_get = IlGetRxIChargerMax();
    }
    #endif
    return ut_IChargerMax_get;
}


uint8_t ut_BChargerIsolationInhibit_get;
uint32_t ut_BChargerIsolationInhibit_get_ctr;
uint8_t ut_IlGetRxBChargerIsolationInhibit(void)
{
    ut_BChargerIsolationInhibit_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_BChargerIsolationInhibit_get = IlGetRxBChargerIsolationInhibit();
    }
    #endif
    return ut_BChargerIsolationInhibit_get;
}


uint8_t ut_NOBC_2Checksum_get;
uint32_t ut_NOBC_2Checksum_get_ctr;
uint8_t ut_IlGetRxNOBC_2Checksum(void)
{
    ut_NOBC_2Checksum_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_NOBC_2Checksum_get = IlGetRxNOBC_2Checksum();
    }
    #endif
    return ut_NOBC_2Checksum_get;
}


uint8_t ut_BChargerDetectBMSFault_get;
uint32_t ut_BChargerDetectBMSFault_get_ctr;
uint8_t ut_IlGetRxBChargerDetectBMSFault(void)
{
    ut_BChargerDetectBMSFault_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_BChargerDetectBMSFault_get = IlGetRxBChargerDetectBMSFault();
    }
    #endif
    return ut_BChargerDetectBMSFault_get;
}


uint8_t ut_BBMSIndicatesFault_get;
uint32_t ut_BBMSIndicatesFault_get_ctr;
uint8_t ut_IlGetRxBBMSIndicatesFault(void)
{
    ut_BBMSIndicatesFault_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_BBMSIndicatesFault_get = IlGetRxBBMSIndicatesFault();
    }
    #endif
    return ut_BBMSIndicatesFault_get;
}


uint16_t ut_VCharger_get;
uint32_t ut_VCharger_get_ctr;
uint16_t ut_IlGetRxVCharger(void)
{
    ut_VCharger_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_VCharger_get = IlGetRxVCharger();
    }
    #endif
    return ut_VCharger_get;
}


uint8_t ut_NChargerStatus_get;
uint32_t ut_NChargerStatus_get_ctr;
uint8_t ut_IlGetRxNChargerStatus(void)
{
    ut_NChargerStatus_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_NChargerStatus_get = IlGetRxNChargerStatus();
    }
    #endif
    return ut_NChargerStatus_get;
}


uint8_t ut_NOBC_2Counter_get;
uint32_t ut_NOBC_2Counter_get_ctr;
uint8_t ut_IlGetRxNOBC_2Counter(void)
{
    ut_NOBC_2Counter_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_NOBC_2Counter_get = IlGetRxNOBC_2Counter();
    }
    #endif
    return ut_NOBC_2Counter_get;
}


uint8_t ut_NChargerHVContactorStatus_get;
uint32_t ut_NChargerHVContactorStatus_get_ctr;
uint8_t ut_IlGetRxNChargerHVContactorStatus(void)
{
    ut_NChargerHVContactorStatus_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_NChargerHVContactorStatus_get = IlGetRxNChargerHVContactorStatus();
    }
    #endif
    return ut_NChargerHVContactorStatus_get;
}


uint16_t ut_NChargerSerialID_get;
uint32_t ut_NChargerSerialID_get_ctr;
uint16_t ut_IlGetRxNChargerSerialID(void)
{
    ut_NChargerSerialID_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_NChargerSerialID_get = IlGetRxNChargerSerialID();
    }
    #endif
    return ut_NChargerSerialID_get;
}


uint8_t ut_BChargerHVFault_get;
uint32_t ut_BChargerHVFault_get_ctr;
uint8_t ut_IlGetRxBChargerHVFault(void)
{
    ut_BChargerHVFault_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_BChargerHVFault_get = IlGetRxBChargerHVFault();
    }
    #endif
    return ut_BChargerHVFault_get;
}


uint8_t ut_ICharger_get;
uint32_t ut_ICharger_get_ctr;
uint8_t ut_IlGetRxICharger(void)
{
    ut_ICharger_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_ICharger_get = IlGetRxICharger();
    }
    #endif
    return ut_ICharger_get;
}


uint8_t ut_NOBC_1Checksum_get;
uint32_t ut_NOBC_1Checksum_get_ctr;
uint8_t ut_IlGetRxNOBC_1Checksum(void)
{
    ut_NOBC_1Checksum_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_NOBC_1Checksum_get = IlGetRxNOBC_1Checksum();
    }
    #endif
    return ut_NOBC_1Checksum_get;
}


uint8_t ut_BChargerFault_get;
uint32_t ut_BChargerFault_get_ctr;
uint8_t ut_IlGetRxBChargerFault(void)
{
    ut_BChargerFault_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_BChargerFault_get = IlGetRxBChargerFault();
    }
    #endif
    return ut_BChargerFault_get;
}


uint8_t ut_BChargerIndicatesEPBInhibit_get;
uint32_t ut_BChargerIndicatesEPBInhibit_get_ctr;
uint8_t ut_IlGetRxBChargerIndicatesEPBInhibit(void)
{
    ut_BChargerIndicatesEPBInhibit_get_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        ut_BChargerIndicatesEPBInhibit_get = IlGetRxBChargerIndicatesEPBInhibit();
    }
    #endif
    return ut_BChargerIndicatesEPBInhibit_get;
}


/* Tx signals source start */
uint8_t ut_BBMSIsolationInhibit_put;
uint32_t ut_BBMSIsolationInhibit_put_ctr;
void ut_IlPutTxBBMSIsolationInhibit(uint8_t val)
{
    ut_BBMSIsolationInhibit_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxBBMSIsolationInhibit(val);
    }
    #endif
    ut_BBMSIsolationInhibit_put = val;
}


uint8_t ut_NChargingCompleteStatus_put;
uint32_t ut_NChargingCompleteStatus_put_ctr;
void ut_IlPutTxNChargingCompleteStatus(uint8_t val)
{
    ut_NChargingCompleteStatus_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNChargingCompleteStatus(val);
    }
    #endif
    ut_NChargingCompleteStatus_put = val;
}


uint8_t ut_BConnectorCheckInhibit_put;
uint32_t ut_BConnectorCheckInhibit_put_ctr;
void ut_IlPutTxBConnectorCheckInhibit(uint8_t val)
{
    ut_BConnectorCheckInhibit_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxBConnectorCheckInhibit(val);
    }
    #endif
    ut_BConnectorCheckInhibit_put = val;
}


uint8_t ut_rBatterySOCCharger_put;
uint32_t ut_rBatterySOCCharger_put_ctr;
void ut_IlPutTxrBatterySOCCharger(uint8_t val)
{
    ut_rBatterySOCCharger_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxrBatterySOCCharger(val);
    }
    #endif
    ut_rBatterySOCCharger_put = val;
}


uint8_t ut_BBMSIndicateChargerFault_put;
uint32_t ut_BBMSIndicateChargerFault_put_ctr;
void ut_IlPutTxBBMSIndicateChargerFault(uint8_t val)
{
    ut_BBMSIndicateChargerFault_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxBBMSIndicateChargerFault(val);
    }
    #endif
    ut_BBMSIndicateChargerFault_put = val;
}


uint8_t ut_NChargerHVContactorReq_put;
uint32_t ut_NChargerHVContactorReq_put_ctr;
void ut_IlPutTxNChargerHVContactorReq(uint8_t val)
{
    ut_NChargerHVContactorReq_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNChargerHVContactorReq(val);
    }
    #endif
    ut_NChargerHVContactorReq_put = val;
}


uint8_t ut_BVehicleAwakeInhibit_put;
uint32_t ut_BVehicleAwakeInhibit_put_ctr;
void ut_IlPutTxBVehicleAwakeInhibit(uint8_t val)
{
    ut_BVehicleAwakeInhibit_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxBVehicleAwakeInhibit(val);
    }
    #endif
    ut_BVehicleAwakeInhibit_put = val;
}


uint8_t ut_B12VSupplyInhibit_put;
uint32_t ut_B12VSupplyInhibit_put_ctr;
void ut_IlPutTxB12VSupplyInhibit(uint8_t val)
{
    ut_B12VSupplyInhibit_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxB12VSupplyInhibit(val);
    }
    #endif
    ut_B12VSupplyInhibit_put = val;
}


uint8_t ut_NBMS_CH1Checksum_put;
uint32_t ut_NBMS_CH1Checksum_put_ctr;
void ut_IlPutTxNBMS_CH1Checksum(uint8_t val)
{
    ut_NBMS_CH1Checksum_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNBMS_CH1Checksum(val);
    }
    #endif
    ut_NBMS_CH1Checksum_put = val;
}


uint8_t ut_BCableFault_put;
uint32_t ut_BCableFault_put_ctr;
void ut_IlPutTxBCableFault(uint8_t val)
{
    ut_BCableFault_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxBCableFault(val);
    }
    #endif
    ut_BCableFault_put = val;
}


uint8_t ut_BBMSFault_put;
uint32_t ut_BBMSFault_put_ctr;
void ut_IlPutTxBBMSFault(uint8_t val)
{
    ut_BBMSFault_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxBBMSFault(val);
    }
    #endif
    ut_BBMSFault_put = val;
}


uint8_t ut_BBMSHVFault_put;
uint32_t ut_BBMSHVFault_put_ctr;
void ut_IlPutTxBBMSHVFault(uint8_t val)
{
    ut_BBMSHVFault_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxBBMSHVFault(val);
    }
    #endif
    ut_BBMSHVFault_put = val;
}


uint8_t ut_IChargerSet_put;
uint32_t ut_IChargerSet_put_ctr;
void ut_IlPutTxIChargerSet(uint8_t val)
{
    ut_IChargerSet_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxIChargerSet(val);
    }
    #endif
    ut_IChargerSet_put = val;
}


uint8_t ut_BEPBInhibit_put;
uint32_t ut_BEPBInhibit_put_ctr;
void ut_IlPutTxBEPBInhibit(uint8_t val)
{
    ut_BEPBInhibit_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxBEPBInhibit(val);
    }
    #endif
    ut_BEPBInhibit_put = val;
}


uint8_t ut_NBMS_CH1Counter_put;
uint32_t ut_NBMS_CH1Counter_put_ctr;
void ut_IlPutTxNBMS_CH1Counter(uint8_t val)
{
    ut_NBMS_CH1Counter_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNBMS_CH1Counter(val);
    }
    #endif
    ut_NBMS_CH1Counter_put = val;
}


uint16_t ut_VChargerSet_put;
uint32_t ut_VChargerSet_put_ctr;
void ut_IlPutTxVChargerSet(uint16_t val)
{
    ut_VChargerSet_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxVChargerSet(val);
    }
    #endif
    ut_VChargerSet_put = val;
}


uint8_t ut_NBMSCommandedMode_put;
uint32_t ut_NBMSCommandedMode_put_ctr;
void ut_IlPutTxNBMSCommandedMode(uint8_t val)
{
    ut_NBMSCommandedMode_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNBMSCommandedMode(val);
    }
    #endif
    ut_NBMSCommandedMode_put = val;
}


uint8_t ut_BBMSVehicleShuttingDownInhibit_put;
uint32_t ut_BBMSVehicleShuttingDownInhibit_put_ctr;
void ut_IlPutTxBBMSVehicleShuttingDownInhibit(uint8_t val)
{
    ut_BBMSVehicleShuttingDownInhibit_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxBBMSVehicleShuttingDownInhibit(val);
    }
    #endif
    ut_BBMSVehicleShuttingDownInhibit_put = val;
}


uint8_t ut_BChargerIndicatesFault_put;
uint32_t ut_BChargerIndicatesFault_put_ctr;
void ut_IlPutTxBChargerIndicatesFault(uint8_t val)
{
    ut_BChargerIndicatesFault_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxBChargerIndicatesFault(val);
    }
    #endif
    ut_BChargerIndicatesFault_put = val;
}


uint8_t ut_BVehicleFault_put;
uint32_t ut_BVehicleFault_put_ctr;
void ut_IlPutTxBVehicleFault(uint8_t val)
{
    ut_BVehicleFault_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxBVehicleFault(val);
    }
    #endif
    ut_BVehicleFault_put = val;
}


uint16_t ut_RBMSHVPos_put;
uint32_t ut_RBMSHVPos_put_ctr;
void ut_IlPutTxRBMSHVPos(uint16_t val)
{
    ut_RBMSHVPos_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxRBMSHVPos(val);
    }
    #endif
    ut_RBMSHVPos_put = val;
}


uint8_t ut_NBMS_CH2Counter_put;
uint32_t ut_NBMS_CH2Counter_put_ctr;
void ut_IlPutTxNBMS_CH2Counter(uint8_t val)
{
    ut_NBMS_CH2Counter_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNBMS_CH2Counter(val);
    }
    #endif
    ut_NBMS_CH2Counter_put = val;
}


uint16_t ut_RBMSHVNeg_put;
uint32_t ut_RBMSHVNeg_put_ctr;
void ut_IlPutTxRBMSHVNeg(uint16_t val)
{
    ut_RBMSHVNeg_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxRBMSHVNeg(val);
    }
    #endif
    ut_RBMSHVNeg_put = val;
}


uint8_t ut_NBMS_CH2Checksum_put;
uint32_t ut_NBMS_CH2Checksum_put_ctr;
void ut_IlPutTxNBMS_CH2Checksum(uint8_t val)
{
    ut_NBMS_CH2Checksum_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNBMS_CH2Checksum(val);
    }
    #endif
    ut_NBMS_CH2Checksum_put = val;
}


uint8_t ut_BIsTetheredToSomething_put;
uint32_t ut_BIsTetheredToSomething_put_ctr;
void ut_IlPutTxBIsTetheredToSomething(uint8_t val)
{
    ut_BIsTetheredToSomething_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxBIsTetheredToSomething(val);
    }
    #endif
    ut_BIsTetheredToSomething_put = val;
}


uint8_t ut_BIsTetheredToActiveCharger_put;
uint32_t ut_BIsTetheredToActiveCharger_put_ctr;
void ut_IlPutTxBIsTetheredToActiveCharger(uint8_t val)
{
    ut_BIsTetheredToActiveCharger_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxBIsTetheredToActiveCharger(val);
    }
    #endif
    ut_BIsTetheredToActiveCharger_put = val;
}


uint8_t ut_BPilotControl_put;
uint32_t ut_BPilotControl_put_ctr;
void ut_IlPutTxBPilotControl(uint8_t val)
{
    ut_BPilotControl_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxBPilotControl(val);
    }
    #endif
    ut_BPilotControl_put = val;
}


uint8_t ut_NPilotStatus_put;
uint32_t ut_NPilotStatus_put_ctr;
void ut_IlPutTxNPilotStatus(uint8_t val)
{
    ut_NPilotStatus_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNPilotStatus(val);
    }
    #endif
    ut_NPilotStatus_put = val;
}


uint8_t ut_NProxStatus_put;
uint32_t ut_NProxStatus_put_ctr;
void ut_IlPutTxNProxStatus(uint8_t val)
{
    ut_NProxStatus_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNProxStatus(val);
    }
    #endif
    ut_NProxStatus_put = val;
}


uint8_t ut_BIsChargerCapableToCharge_put;
uint32_t ut_BIsChargerCapableToCharge_put_ctr;
void ut_IlPutTxBIsChargerCapableToCharge(uint8_t val)
{
    ut_BIsChargerCapableToCharge_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxBIsChargerCapableToCharge(val);
    }
    #endif
    ut_BIsChargerCapableToCharge_put = val;
}


int16_t ut_VPackBMS_put;
uint32_t ut_VPackBMS_put_ctr;
void ut_IlPutTxVPackBMS(int16_t val)
{
    ut_VPackBMS_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxVPackBMS(val);
    }
    #endif
    ut_VPackBMS_put = val;
}


uint8_t ut_BIsTetheredToCharger_put;
uint32_t ut_BIsTetheredToCharger_put_ctr;
void ut_IlPutTxBIsTetheredToCharger(uint8_t val)
{
    ut_BIsTetheredToCharger_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxBIsTetheredToCharger(val);
    }
    #endif
    ut_BIsTetheredToCharger_put = val;
}


uint8_t ut_BIsTetheredToNothing_put;
uint32_t ut_BIsTetheredToNothing_put_ctr;
void ut_IlPutTxBIsTetheredToNothing(uint8_t val)
{
    ut_BIsTetheredToNothing_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxBIsTetheredToNothing(val);
    }
    #endif
    ut_BIsTetheredToNothing_put = val;
}


uint8_t ut_BIsChargerReady_put;
uint32_t ut_BIsChargerReady_put_ctr;
void ut_IlPutTxBIsChargerReady(uint8_t val)
{
    ut_BIsChargerReady_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxBIsChargerReady(val);
    }
    #endif
    ut_BIsChargerReady_put = val;
}


uint8_t ut_Additional_BMS_Errors_Chg_1_put;
uint32_t ut_Additional_BMS_Errors_Chg_1_put_ctr;
void ut_IlPutTxAdditional_BMS_Errors_Chg_1(uint8_t val)
{
    ut_Additional_BMS_Errors_Chg_1_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxAdditional_BMS_Errors_Chg_1(val);
    }
    #endif
    ut_Additional_BMS_Errors_Chg_1_put = val;
}


uint8_t ut_Additional_BMS_Errors_Chg_3_put;
uint32_t ut_Additional_BMS_Errors_Chg_3_put_ctr;
void ut_IlPutTxAdditional_BMS_Errors_Chg_3(uint8_t val)
{
    ut_Additional_BMS_Errors_Chg_3_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxAdditional_BMS_Errors_Chg_3(val);
    }
    #endif
    ut_Additional_BMS_Errors_Chg_3_put = val;
}


uint8_t ut_Additional_BMS_Errors_Chg_2_put;
uint32_t ut_Additional_BMS_Errors_Chg_2_put_ctr;
void ut_IlPutTxAdditional_BMS_Errors_Chg_2(uint8_t val)
{
    ut_Additional_BMS_Errors_Chg_2_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxAdditional_BMS_Errors_Chg_2(val);
    }
    #endif
    ut_Additional_BMS_Errors_Chg_2_put = val;
}


uint8_t ut_BCtcNegVehHs_put;
uint32_t ut_BCtcNegVehHs_put_ctr;
void ut_IlPutTxBCtcNegVehHs(uint8_t val)
{
    ut_BCtcNegVehHs_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxBCtcNegVehHs(val);
    }
    #endif
    ut_BCtcNegVehHs_put = val;
}


uint8_t ut_NChgLastResult_put;
uint32_t ut_NChgLastResult_put_ctr;
void ut_IlPutTxNChgLastResult(uint8_t val)
{
    ut_NChgLastResult_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNChgLastResult(val);
    }
    #endif
    ut_NChgLastResult_put = val;
}


uint8_t ut_NChgState_put;
uint32_t ut_NChgState_put_ctr;
void ut_IlPutTxNChgState(uint8_t val)
{
    ut_NChgState_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNChgState(val);
    }
    #endif
    ut_NChgState_put = val;
}


uint8_t ut_BCtcPosChgLs_put;
uint32_t ut_BCtcPosChgLs_put_ctr;
void ut_IlPutTxBCtcPosChgLs(uint8_t val)
{
    ut_BCtcPosChgLs_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxBCtcPosChgLs(val);
    }
    #endif
    ut_BCtcPosChgLs_put = val;
}


uint8_t ut_NCcoState_put;
uint32_t ut_NCcoState_put_ctr;
void ut_IlPutTxNCcoState(uint8_t val)
{
    ut_NCcoState_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNCcoState(val);
    }
    #endif
    ut_NCcoState_put = val;
}


uint8_t ut_BCtcNegVehLs_put;
uint32_t ut_BCtcNegVehLs_put_ctr;
void ut_IlPutTxBCtcNegVehLs(uint8_t val)
{
    ut_BCtcNegVehLs_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxBCtcNegVehLs(val);
    }
    #endif
    ut_BCtcNegVehLs_put = val;
}


uint8_t ut_BCtcPosChgHs_put;
uint32_t ut_BCtcPosChgHs_put_ctr;
void ut_IlPutTxBCtcPosChgHs(uint8_t val)
{
    ut_BCtcPosChgHs_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxBCtcPosChgHs(val);
    }
    #endif
    ut_BCtcPosChgHs_put = val;
}


int16_t ut_VChgPosBMS_put;
uint32_t ut_VChgPosBMS_put_ctr;
void ut_IlPutTxVChgPosBMS(int16_t val)
{
    ut_VChgPosBMS_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxVChgPosBMS(val);
    }
    #endif
    ut_VChgPosBMS_put = val;
}


uint8_t ut_BCtcNegChgHs_put;
uint32_t ut_BCtcNegChgHs_put_ctr;
void ut_IlPutTxBCtcNegChgHs(uint8_t val)
{
    ut_BCtcNegChgHs_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxBCtcNegChgHs(val);
    }
    #endif
    ut_BCtcNegChgHs_put = val;
}


int16_t ut_VChgNegBMS_put;
uint32_t ut_VChgNegBMS_put_ctr;
void ut_IlPutTxVChgNegBMS(int16_t val)
{
    ut_VChgNegBMS_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxVChgNegBMS(val);
    }
    #endif
    ut_VChgNegBMS_put = val;
}


uint8_t ut_BCtcNegChgLs_put;
uint32_t ut_BCtcNegChgLs_put_ctr;
void ut_IlPutTxBCtcNegChgLs(uint8_t val)
{
    ut_BCtcNegChgLs_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxBCtcNegChgLs(val);
    }
    #endif
    ut_BCtcNegChgLs_put = val;
}


int32_t ut_IChargerBMS_put;
uint32_t ut_IChargerBMS_put_ctr;
void ut_IlPutTxIChargerBMS(int32_t val)
{
    ut_IChargerBMS_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxIChargerBMS(val);
    }
    #endif
    ut_IChargerBMS_put = val;
}


uint16_t ut_VCellMinBMS_put;
uint32_t ut_VCellMinBMS_put_ctr;
void ut_IlPutTxVCellMinBMS(uint16_t val)
{
    ut_VCellMinBMS_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxVCellMinBMS(val);
    }
    #endif
    ut_VCellMinBMS_put = val;
}


uint16_t ut_VCellMaxBMS_put;
uint32_t ut_VCellMaxBMS_put_ctr;
void ut_IlPutTxVCellMaxBMS(uint16_t val)
{
    ut_VCellMaxBMS_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxVCellMaxBMS(val);
    }
    #endif
    ut_VCellMaxBMS_put = val;
}


int16_t ut_VPilotPin_put;
uint32_t ut_VPilotPin_put_ctr;
void ut_IlPutTxVPilotPin(int16_t val)
{
    ut_VPilotPin_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxVPilotPin(val);
    }
    #endif
    ut_VPilotPin_put = val;
}


uint8_t ut_NBMSState_put;
uint32_t ut_NBMSState_put_ctr;
void ut_IlPutTxNBMSState(uint8_t val)
{
    ut_NBMSState_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNBMSState(val);
    }
    #endif
    ut_NBMSState_put = val;
}


uint16_t ut_NBMSChargeInhibitMask_put;
uint32_t ut_NBMSChargeInhibitMask_put_ctr;
void ut_IlPutTxNBMSChargeInhibitMask(uint16_t val)
{
    ut_NBMSChargeInhibitMask_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNBMSChargeInhibitMask(val);
    }
    #endif
    ut_NBMSChargeInhibitMask_put = val;
}


int16_t ut_VProxPin_put;
uint32_t ut_VProxPin_put_ctr;
void ut_IlPutTxVProxPin(int16_t val)
{
    ut_VProxPin_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxVProxPin(val);
    }
    #endif
    ut_VProxPin_put = val;
}


uint8_t ut_NTermReason_put;
uint32_t ut_NTermReason_put_ctr;
void ut_IlPutTxNTermReason(uint8_t val)
{
    ut_NTermReason_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNTermReason(val);
    }
    #endif
    ut_NTermReason_put = val;
}


uint8_t ut_NBMS_Diag_15_put[8];
uint32_t ut_NBMS_Diag_15_put_ctr;
void ut_IlPutTxNBMS_Diag_15(uint8_t * val)
{
    ut_NBMS_Diag_15_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNBMS_Diag_15(val);
    }
    #endif
    ut_memcpy(ut_NBMS_Diag_15_put, val, sizeof(ut_NBMS_Diag_15_put));
}


uint8_t ut_NBMS_Diag_16_put[8];
uint32_t ut_NBMS_Diag_16_put_ctr;
void ut_IlPutTxNBMS_Diag_16(uint8_t * val)
{
    ut_NBMS_Diag_16_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNBMS_Diag_16(val);
    }
    #endif
    ut_memcpy(ut_NBMS_Diag_16_put, val, sizeof(ut_NBMS_Diag_16_put));
}


uint8_t ut_NBMS_Diag_14_put[8];
uint32_t ut_NBMS_Diag_14_put_ctr;
void ut_IlPutTxNBMS_Diag_14(uint8_t * val)
{
    ut_NBMS_Diag_14_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNBMS_Diag_14(val);
    }
    #endif
    ut_memcpy(ut_NBMS_Diag_14_put, val, sizeof(ut_NBMS_Diag_14_put));
}


uint8_t ut_NBMS_Diag_13_put[8];
uint32_t ut_NBMS_Diag_13_put_ctr;
void ut_IlPutTxNBMS_Diag_13(uint8_t * val)
{
    ut_NBMS_Diag_13_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNBMS_Diag_13(val);
    }
    #endif
    ut_memcpy(ut_NBMS_Diag_13_put, val, sizeof(ut_NBMS_Diag_13_put));
}


uint8_t ut_NBMS_Diag_10_put[8];
uint32_t ut_NBMS_Diag_10_put_ctr;
void ut_IlPutTxNBMS_Diag_10(uint8_t * val)
{
    ut_NBMS_Diag_10_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNBMS_Diag_10(val);
    }
    #endif
    ut_memcpy(ut_NBMS_Diag_10_put, val, sizeof(ut_NBMS_Diag_10_put));
}


uint8_t ut_NBMS_Diag_09_put[8];
uint32_t ut_NBMS_Diag_09_put_ctr;
void ut_IlPutTxNBMS_Diag_09(uint8_t * val)
{
    ut_NBMS_Diag_09_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNBMS_Diag_09(val);
    }
    #endif
    ut_memcpy(ut_NBMS_Diag_09_put, val, sizeof(ut_NBMS_Diag_09_put));
}


uint8_t ut_NBMS_Diag_12_put[8];
uint32_t ut_NBMS_Diag_12_put_ctr;
void ut_IlPutTxNBMS_Diag_12(uint8_t * val)
{
    ut_NBMS_Diag_12_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNBMS_Diag_12(val);
    }
    #endif
    ut_memcpy(ut_NBMS_Diag_12_put, val, sizeof(ut_NBMS_Diag_12_put));
}


uint8_t ut_NBMS_Diag_11_put[8];
uint32_t ut_NBMS_Diag_11_put_ctr;
void ut_IlPutTxNBMS_Diag_11(uint8_t * val)
{
    ut_NBMS_Diag_11_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNBMS_Diag_11(val);
    }
    #endif
    ut_memcpy(ut_NBMS_Diag_11_put, val, sizeof(ut_NBMS_Diag_11_put));
}


uint8_t ut_NBMS_Diag_06_put[8];
uint32_t ut_NBMS_Diag_06_put_ctr;
void ut_IlPutTxNBMS_Diag_06(uint8_t * val)
{
    ut_NBMS_Diag_06_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNBMS_Diag_06(val);
    }
    #endif
    ut_memcpy(ut_NBMS_Diag_06_put, val, sizeof(ut_NBMS_Diag_06_put));
}


int16_t ut_VVehNegBMS_put;
uint32_t ut_VVehNegBMS_put_ctr;
void ut_IlPutTxVVehNegBMS(int16_t val)
{
    ut_VVehNegBMS_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxVVehNegBMS(val);
    }
    #endif
    ut_VVehNegBMS_put = val;
}


int16_t ut_VVehPosBMS_put;
uint32_t ut_VVehPosBMS_put_ctr;
void ut_IlPutTxVVehPosBMS(int16_t val)
{
    ut_VVehPosBMS_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxVVehPosBMS(val);
    }
    #endif
    ut_VVehPosBMS_put = val;
}


uint8_t ut_NBMS_Diag_08_put[8];
uint32_t ut_NBMS_Diag_08_put_ctr;
void ut_IlPutTxNBMS_Diag_08(uint8_t * val)
{
    ut_NBMS_Diag_08_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNBMS_Diag_08(val);
    }
    #endif
    ut_memcpy(ut_NBMS_Diag_08_put, val, sizeof(ut_NBMS_Diag_08_put));
}


uint8_t ut_NBMS_Diag_07_put[8];
uint32_t ut_NBMS_Diag_07_put_ctr;
void ut_IlPutTxNBMS_Diag_07(uint8_t * val)
{
    ut_NBMS_Diag_07_put_ctr++;
    #ifndef HOSTED
    if (!ut_cbd_override)
    {
        IlPutTxNBMS_Diag_07(val);
    }
    #endif
    ut_memcpy(ut_NBMS_Diag_07_put, val, sizeof(ut_NBMS_Diag_07_put));
}


/* Rx groups source start */
/* Tx groups source start */
