##############################################################################
# $Id: canbedded.mk 8819 2013-06-05 16:29:44Z gvs $
##############################################################################
#
# Makefile fragment for CANbedded
#
##############################################################################

FEAT_NAME:=canbedded

ifneq ($(VERBOSE),0)
    $(info Including feature $(FEAT_NAME))
endif

FEAT_DIR:=$(PROTO_ROOT)/$(FEAT_NAME)

# CANbedded source code is split between the following directories:
# 	fixed:	Vector source code we mustn't touch
# 	mod:	Vector source code we need to todge
# 	gen:	Code generated by GENy
#
# The prodder and platform_test shares the fixed, mod and callbacks directories with the
# application but has its own gen/ directory elsewhere

CANBEDDED_SRC_DIRS:=$(FEAT_DIR)/fixed $(FEAT_DIR)/mod
# prodder and platform_test generated code lives under the prodder or platform_test
ifndef PLATFORM_TEST
ifndef PRODDER
CANBEDDED_SRC_DIRS+=$(FEAT_DIR)/gen
endif
endif

# CANBEDDED_SRC_DIRS need to be on the vpath for .c files
ADDITIONAL_SRC_DIRS+=$(CANBEDDED_SRC_DIRS)
# and on the include path
ADDITIONAL_INC_DIRS+=$(CANBEDDED_SRC_DIRS)

CB_FIX_SRC:= \
	can_drv.c \
	can_isr.c \
	ccl.c \
	il.c \
	sip_vers.c \
	vstdlib.c
	
CB_MOD_SRC:=

ifndef PRODDER
# Add XCP files to CB_FIX_SRC and CB_MOD_SRC
CB_FIX_SRC:=$(CB_FIX_SRC) \
    xcp_can.c \
    xcpprof.c \
    n_onm.c

CB_MOD_SRC:=$(CB_MOD_SRC) xcp_appl.c

ifndef PLATFORM_TEST
CB_FIX_SRC:=$(CB_FIX_SRC) \
	tpmc.c
CB_GEN_SRC:= \
	DrvCan_Mcs12xMscanHll.c \
	can_par.c \
	ccl_par.c \
	drv_par.c \
	il_par.c \
	v_par.c \
	xcp_par.c \
	nm_par.c \
	desc.c \
	tp_par.c

CB_MOD_SRC:=$(CB_MOD_SRC) appdesc_implemented.c
endif
else
# This is a prodder build
#
CB_FIX_SRC:=$(CB_FIX_SRC) \
    n_onm.c \
    tpmc.c

endif
# platform_test and prodder generated code lives under 
# respective directory

CB_SRC=$(CB_FIX_SRC) $(CB_MOD_SRC) $(CB_GEN_SRC)
SRCFILES+=$(CB_SRC)
# we don't want the CANbedded source files included in static check
CHECK_EXCLUDE+=$(CB_SRC)    
# and we won't find any ASAP mark-up in them either
A2LSCAN_EXCLUDE+=$(CB_SRC)

# Doxygen documentation files
# Note that += wouldn't work because we need the current value of FEAT_NAME
DOTDOXFILES:=$(DOTDOXFILES) $(PROTO_ROOT)/$(FEAT_NAME)/canbedded.dox
